<h2> Análise exploratória do CEMADEN para São Paulo </h2>

## Objetivo
Este notebook reúne a etapa inicial de exploração do conjunto de dados do CEMADEN, com foco em:
- carga e integração das tabelas de leitura, estação e sensor;
- validação básica da qualidade dos dados;
- análise espacial por zona da cidade;
- avaliação do comportamento de precipitação e do status das estações.

## Estratégia de análise
1. Carregar as tabelas do banco;
2. validar chaves e campos essenciais;
3. filtrar os dados de São Paulo;
4. enriquecer com zona geográfica e status das estações;
5. verificar qualidade, distribuições e padrões temporais.

> A análise abaixo foi organizada para dar suporte ao entendimento do dado antes de formular conclusões finais do projeto.

In [ ]:
import os
import pandas as pd
from sqlalchemy import create_engine, inspect

RAIZ = r"C:\TI\Projetos Univesp\Projeto - 4"

In [ ]:
dadosUrl = "postgresql://noaa_user:C53AONMRWKIZ3nlrVkQPpGMVmWjNNpyu@dpg-da6a5oqjnfac73aajj5g-a.oregon-postgres.render.com/noaa?sslmode=require"

In [ ]:
engine = create_engine(dadosUrl)
inspector = inspect(engine)
print(inspector.get_table_names())

In [33]:
df_cemaden = pd.read_csv(os.path.join(RAIZ, "docs/csv/cemaden", "cemaden.csv"), sep=",")
print(f"Total de registros em SP: {len(df_cemaden)}")
df_cemaden.head(5)

Total de registros em SP: 8174

,id_reading,station_code,sensor_id,nome,uf,latitude,longitude,description,station_type_description,observation_date,value,qualification,collected_at_reading,id_sensor,collected_at_sensor,updated_at
0,1,354820301A,240,Centro,SP,-22.83151,-45.66007,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:49.627,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
1,2,350450302A,240,Centro,SP,-23.10100,-48.92000,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:51.034,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
2,3,353180301A,240,Santa Cruz,SP,-22.90500,-47.34300,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:51.246,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
3,4,353440103A,240,Rochdale,SP,-23.50700,-46.77600,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:51.456,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
4,5,355240301A,240,Vila Miranda,SP,-22.82600,-47.27700,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:51.665,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238

In [49]:
prefixo = "3550308"

df_registro = df_cemaden[
    df_cemaden["station_code"].astype(str).str.startswith(prefixo)
].copy()

print(df_registro.shape[0])
df_registro.head(5)

950

,id_reading,station_code,sensor_id,nome,uf,latitude,longitude,description,station_type_description,observation_date,value,qualification,collected_at_reading,id_sensor,collected_at_sensor,updated_at
18,19,355030873A,10,Perus,SP,-23.407,-46.753,Chuva,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:54.608,10,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033
24,25,355030824A,240,Jardim Angela,SP,-23.697,-46.765,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:55.884,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
49,50,355030806A,240,Cidade Tiradentes 2,SP,-23.580,-46.383,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:45:01.202,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
50,51,355030806A,10,Cidade Tiradentes 2,SP,-23.580,-46.383,Chuva,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:45:01.411,10,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033
51,52,355030846A,10,Butantã,SP,-23.589,-46.738,Chuva,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:45:01.620,10,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033

In [50]:
pos = df_registro.columns.get_loc("uf")

df_registro.insert(pos + 1, "city", "São Paulo")

print(df_registro.shape[0])
df_registro.head(5)

950

,id_reading,station_code,sensor_id,nome,uf,city,latitude,longitude,description,station_type_description,observation_date,value,qualification,collected_at_reading,id_sensor,collected_at_sensor,updated_at
18,19,355030873A,10,Perus,SP,São Paulo,-23.407,-46.753,Chuva,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:54.608,10,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033
24,25,355030824A,240,Jardim Angela,SP,São Paulo,-23.697,-46.765,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:55.884,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
49,50,355030806A,240,Cidade Tiradentes 2,SP,São Paulo,-23.580,-46.383,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:45:01.202,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
50,51,355030806A,10,Cidade Tiradentes 2,SP,São Paulo,-23.580,-46.383,Chuva,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:45:01.411,10,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033
51,52,355030846A,10,Butantã,SP,São Paulo,-23.589,-46.738,Chuva,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:45:01.620,10,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033

In [29]:
df_cemaden = df_cemaden.rename(columns={"nome": "city"})

In [32]:
df_cemaden_sp = df_cemaden[
    df_cemaden["city"] == "Sao Paulo"
].copy()
print(f"Total de registros em SP: {len(df_cemaden_sp)}")
df_cemaden_sp.head(5)

Total de registros em SP: 0

Empty DataFrame
Columns: [id_reading, station_code, sensor_id, city, uf, latitude, longitude, description, station_type_description, observation_date, value, qualification, collected_at_reading, id_sensor, collected_at_sensor, updated_at]
Index: []

In [57]:
from sqlalchemy import create_engine, inspect, URL, text

bd_config = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password=211980,
    host="localhost",
    port=5432,
    database="postgres",
)

engine_local = create_engine(bd_config)

In [ ]:
df_cemaden.to_sql(
    name ="df_cemanden",
    con=engine_local,
    if_exists="append",
    index=False,
    method="multi",
)

In [ ]:
df_reading = pd.read_sql("SELECT * FROM cemaden_reading", engine)
df_station = pd.read_sql("SELECT * FROM cemaden_station", engine)
df_sensor  = pd.read_sql("SELECT * FROM cemaden_sensor", engine)

print(f"Leituras:  {len(df_reading)}")
print(f"Estações:  {len(df_station)}")
print(f"Sensores:  {len(df_sensor)}")

#CAMINHO_READING = os.path.join(RAIZ, "df_reading.xlsx")
#try:
#    import openpyxl
#except ModuleNotFoundError:
#    import subprocess
#    import sys
#    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'openpyxl'])
#    import openpyxl
#CAMINHO_STATION = os.path.join(RAIZ, "df_station.xlsx")
#CAMINHO_SENSOR = os.path.join(RAIZ, "df_sensor.xlsx")

#df_reading.to_excel(CAMINHO_READING, index=False)
#df_station.to_excel(CAMINHO_STATION, index=False)
#df_sensor.to_excel(CAMINHO_SENSOR, index=False)

#print("Arquivos Excel salvos:")
#print(CAMINHO_READING)
#print(CAMINHO_STATION)
#print(CAMINHO_SENSOR)

In [ ]:
pos = df_reading.columns.get_loc('sensor_id')

for col in ['nome', 'uf', 'latitude', 'longitude']:
    if col in df_reading.columns:
        df_reading = df_reading.drop(columns=[col])

df_reading.insert(pos + 1, 'nome', df_reading['raw_payload'].apply(lambda x: x.get('nome')))
df_reading.insert(pos + 2, 'uf', df_reading['raw_payload'].apply(lambda x: x.get('uf')))
df_reading.insert(pos + 3, 'latitude', df_reading['raw_payload'].apply(lambda x: x.get('latitude')))
df_reading.insert(pos + 4, 'longitude', df_reading['raw_payload'].apply(lambda x: x.get('longitude')))
df_reading.drop(columns=['raw_payload'], inplace=True)      

#print(df_reading['raw_payload'].iloc[0])
df_reading

In [ ]:
df_reading['sensor_id'] = df_reading['sensor_id'].astype(str).str.strip()
df_sensor['id'] = df_sensor['id'].astype(str).str.strip()
match = df_reading['sensor_id'].isin(df_sensor['id'])
print(f"Casam: {match.sum()} de {len(df_reading)} linhas")

In [ ]:
df_cemaden = df_reading.merge(
    df_sensor, left_on='sensor_id',
    right_on='id', how='left',
    validate='many_to_one',
    suffixes=('_reading', '_sensor')
)

cols = df_cemaden.columns.tolist()
cols.remove('description')
pos = cols.index('longitude') + 1
cols.insert(pos, 'description')
df_cemaden = df_cemaden[cols]

df_cemaden.drop(columns=['id_sensor', 'collected_at_sensor'], inplace=True)
df_cemaden.rename(columns={'id_reading': 'id', 'collected_at_reading': 'collected_at'}, inplace=True)
df_cemaden

In [ ]:
print("Linhas:", len(df_cemaden))
print("id max:", df_cemaden['id_reading'].max())
print("ids únicos:", df_cemaden['id_reading'].nunique())
print("Faltam ids (gaps):", df_cemaden['id_reading'].max() - df_cemaden['id_reading'].nunique() + 1)

In [ ]:
print(df_station['raw_payload'].iloc[0])

In [ ]:
existentes = df_reading['station_code'].isin(df_station['station_code'])
print(f"{existentes.sum()} de {len(df_reading)} linhas")

In [ ]:
nao_cadastradas = set(df_reading['station_code']) - set(df_station['station_code'])
print("Leituras com estação não cadastrada:", nao_cadastradas)

In [ ]:
print("Estaçoes com pelo menos 1 leitura:", df_reading['station_code'].nunique())
print("Total de estaçoes cadastradas:", df_station['station_code'].nunique())
print("Estações sem leitura:", df_station['station_code'].nunique() - df_reading['station_code'].nunique())
print(set(df_reading['station_code']) <= set(df_station['station_code']))

In [ ]:
df_station['station_type_description'].value_counts()
#df_station.isna().sum()
#print(df_station['raw_payload'].iloc[0])

In [ ]:
df_cemaden = df_cemaden.merge(
    df_station[['station_code', 'station_type_description']],
    on='station_code',
    how='left',
    validate='many_to_one',
    suffixes=('_reading', '_station')
)

colunas = df_cemaden.columns.tolist()
colunas.remove('station_type_description')
colunas.insert(colunas.index('description') + 1, 'station_type_description')
df_cemaden = df_cemaden[colunas]
df_cemaden.to_csv(os.path.join(RAIZ, "docs/cemaden.csv"), index=False)

df_cemaden.to_csv(os.path.join(RAIZ, "docs/cemaden.csv"), index=False)

df_cemaden

In [ ]:
stations_com_leitura = set(df_cemaden["station_code"])
df_cemaden["tem_leitura"] = df_cemaden["station_code"].isin(stations_com_leitura)
print(df_cemaden["tem_leitura"].value_counts())

In [54]:
import geopandas as gpd

zonas = gpd.read_file(os.path.join(RAIZ, "zonas_sp.geojson"))

# Expande as zonas em 100 m (EPSG:31983) para incluir Cidade Tiradentes 2 (~34 m fora da Leste)
zonas["geometry"] = zonas.to_crs("EPSG:31983").geometry.buffer(40).to_crs("EPSG:4326").geometry

gdf = gpd.GeoDataFrame(
    df_registro,
    geometry=gpd.points_from_xy(df_registro["longitude"], df_registro["latitude"]),
    crs="EPSG:4326",
)
gdf = gpd.sjoin(gdf, zonas, how="left", predicate="within")
gdf["zona"] = gdf["zona"].fillna("Fora de SP")

df_station_sp = gdf.drop(columns=["geometry", "index_right"]).copy()

df_plot = df_station_sp.merge(
    df_registro[["id_reading", "description"]],
    on="id_reading",
    how="left"
)

df_plot = df_plot[
    df_plot["zona"].isin(["Sul", "Leste", "Norte", "Oeste", "Centro"])
].copy()
print(df_plot["zona"].value_counts())

zona
Sul       436
Leste     234
Norte     158
Oeste      84
Centro     38
Name: count, dtype: int64

In [55]:
cols = list(df_plot.columns)
uf_idx = cols.index("nome")
zona_idx = cols.index("zona")

cols.insert(uf_idx + 1, cols.pop(zona_idx))
df_plot = df_plot[cols]

In [ ]:
print("Número de registros", df_plot.shape[0])
df_plot.head(5)

In [ ]:
d_reading	station_code	sensor_id	nome	uf	city	latitude	longitude	description	station_type_description	observation_date	value	qualification	collected_at_reading	id_sensor	collected_at_sensor	updated_at

In [56]:
colunas_uteis = [
    "id_reading",
    "station_code",
    "sensor_id",
    "nome",
    "zona",
    "uf",
    "city",
    "latitude",
    "longitude",
    "description",
    "station_type_description",
    "observation_date",
    "value",
    "qualification",
    "collected_at_reading",
    "collected_at_sensor",
    "updated_at"
]

df_plot = df_plot[colunas_uteis]
df_plot.head(5)

,id_reading,station_code,sensor_id,nome,zona,uf,city,latitude,longitude,description,station_type_description,observation_date,value,qualification,collected_at_reading,collected_at_sensor,updated_at
0,19,355030873A,10,Perus,Norte,SP,São Paulo,-23.407,-46.753,Chuva,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:54.608,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033
1,25,355030824A,240,Jardim Angela,Sul,SP,São Paulo,-23.697,-46.765,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:44:55.884,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
2,50,355030806A,240,Cidade Tiradentes 2,Leste,SP,São Paulo,-23.580,-46.383,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:45:01.202,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
3,51,355030806A,10,Cidade Tiradentes 2,Leste,SP,São Paulo,-23.580,-46.383,Chuva,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:45:01.411,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033
4,52,355030846A,10,Butantã,Oeste,SP,São Paulo,-23.589,-46.738,Chuva,Pluviométrica,2026-08-28 15:50:00,0.0,0,2026-08-28 18:45:01.620,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033

In [58]:
df_plot.to_sql(
    name ="df_cemanden_station",
    con=engine_local,
    if_exists="append",
    index=False,
    method="multi",
)

950

In [61]:
# Agrupando os dados do CEMADEN por Ano, Trimestre e Região
# (cria as colunas exigidas a partir das colunas reais do DataFrame df_plot)
df_cemaden_agrupado = (
    df_plot.assign(
        Ano=pd.to_datetime(df_plot["observation_date"]).dt.year,
        Trimestre=pd.to_datetime(df_plot["observation_date"]).dt.quarter,
        Regiao=df_plot["zona"],
        Valor=df_plot["value"],
    )
    .groupby(["Ano", "Trimestre", "Regiao"], as_index=False)
    .agg(
        Media_Chuva_240m=("Valor", "mean"),
        Total_Chuva=("Valor", "sum"),
        Eventos_Extremos=("Valor", lambda x: (x > 10).sum()),
    )
)

df_cemaden_agrupado.head()

    Ano  Trimestre  Regiao  Media_Chuva_240m  Total_Chuva  Eventos_Extremos
0  2026          3  Centro          0.221053      8.40000                 0
1  2026          3   Leste          0.082051     19.20000                 0
2  2026          3   Norte          1.253447    198.04468                 1
3  2026          3   Oeste          0.042857      3.60000                 0
4  2026          3     Sul          0.239353    104.35783                 0

In [59]:
# Mapa das estacoes com pinos coloridos por zona (Icon)
import folium

cores = {
    "Centro": "gray",
    "Norte": "darkblue",
    "Sul": "darkgreen",
    "Leste": "red",
    "Oeste": "darkred",
}

m = folium.Map(
    location=[df_station_sp["latitude"].mean(), df_station_sp["longitude"].mean()],
    zoom_start=12,
)

folium.TileLayer(
    tiles="https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}",
    attr="Google",
    name="Google Maps",
).add_to(m)

for _, r in df_plot.iterrows():
    cor = cores.get(r["zona"], "gray")
    nome = r.get("nome", r.get("name", "Estação"))
    folium.Marker(
        location=[r["latitude"], r["longitude"]],
        popup=f"{nome} - {r['zona']}",
        tooltip=nome,
        icon=folium.Icon(color=cor)
    ).add_to(m)

CAMINHO = os.path.join(RAIZ, "stations_map.html")
m.save(CAMINHO)
print("Mapa salvo em:", CAMINHO)
m

Mapa salvo em: C:\TI\Projetos Univesp\Projeto - 4\stations_map.html