In [ ]:
import os
import pandas as pd
from sqlalchemy import create_engine, inspect

RAIZ = r"C:\TI\Projetos Univesp\Projeto - 4"

In [22]:
dadosUrl = "postgresql://noaa_user:C53AONMRWKIZ3nlrVkQPpGMVmWjNNpyu@dpg-da6a5oqjnfac73aajj5g-a.oregon-postgres.render.com/noaa?sslmode=require"

In [23]:
engine = create_engine(dadosUrl)
inspector = inspect(engine)
print(inspector.get_table_names())

['ana_telemetry_reading', 'cemaden_sensor', 'cemaden_station', 'cemaden_reading', 'noaa_enso_weekly', 'ana_station']

In [4]:
df = pd.read_sql("SELECT * FROM cemaden_station", engine)
df.isna().sum()

id_estacao                    0
station_code                  0
ibge_code                     0
name                          0
city                          0
state                         0
latitude                      0
longitude                     0
altitude                      0
network_id                    0
network_acronym               0
station_type_id               0
station_type_description      0
cota_alerta                 697
cota_atencao                697
cota_transbordamento        697
installation_date             0
registration_date             0
last_transmission             0
inactive_since                0
raw_payload                   0
collected_at                  0
updated_at                    0
dtype: int64

In [5]:
df_sp = df[df['ibge_code'] == 3550308]  # Filter for São Paulo (IBGE code 3550308)
df_sp

,id_estacao,station_code,ibge_code,name,city,state,latitude,longitude,altitude,network_id,...,cota_alerta,cota_atencao,cota_transbordamento,installation_date,registration_date,last_transmission,inactive_since,raw_payload,collected_at,updated_at
79,3830,355030899A,3550308,Jardim Eledy,SÃO PAULO,SP,-23.649000,-46.786000,0.0,11,...,NaN,NaN,NaN,2013-11-14 14:18:51.509,2013-11-14 14:18:51.509,2024-06-04 01:50:33,2024-06-04 03:54:15.996,"{'uf': 'SP', 'nome': 'Jardim Eledy', 'cidade':...",2026-08-28 18:18:07.657,2026-09-15 17:52:08.879
80,3829,355030898A,3550308,Jardim Romano,SÃO PAULO,SP,-23.478880,-46.381210,0.0,11,...,NaN,NaN,NaN,2014-12-02 20:31:16.994,2014-12-02 20:31:16.994,2026-09-15 11:50:38,2026-09-02 16:51:33.056,"{'uf': 'SP', 'nome': 'Jardim Romano', 'cidade'...",2026-08-28 18:18:07.863,2026-09-15 17:52:09.088
81,3828,355030897A,3550308,Jaguaré,SÃO PAULO,SP,-23.550000,-46.743000,0.0,11,...,NaN,NaN,NaN,2013-11-08 13:21:13.032,2013-11-08 13:21:13.032,2026-09-15 11:40:29,2026-03-07 05:50:27.726,"{'uf': 'SP', 'nome': 'Jaguaré', 'cidade': 'SÃO...",2026-08-28 18:18:08.070,2026-09-15 17:52:09.299
82,3827,355030896A,3550308,Jardim João XXIII,SÃO PAULO,SP,-23.600000,-46.789000,0.0,11,...,NaN,NaN,NaN,2013-11-12 11:27:25.428,2013-11-12 11:27:25.428,2026-09-15 11:55:47,2026-06-09 16:32:30.437,"{'uf': 'SP', 'nome': 'Jardim João XXIII', 'cid...",2026-08-28 18:18:08.284,2026-09-15 17:52:09.507
83,3826,355030895A,3550308,Pirajussara,SÃO PAULO,SP,-23.638000,-46.780000,0.0,11,...,NaN,NaN,NaN,2013-11-07 17:16:18.954,2013-11-07 17:16:18.954,2026-09-14 14:33:16,2026-09-14 16:38:22.561,"{'uf': 'SP', 'nome': 'Pirajussara', 'cidade': ...",2026-08-28 18:18:08.490,2026-09-15 17:52:09.714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,4399,355030822B,3550308,Avenida Oratório,SÃO PAULO,SP,-23.613000,-46.523000,0.0,11,...,NaN,NaN,NaN,2013-12-16 13:23:27.225,2013-12-16 13:23:27.225,2026-09-15 07:20:25,2026-09-15 09:25:53.503,"{'uf': 'SP', 'nome': 'Avenida Oratório', 'cida...",2026-08-28 18:18:19.334,2026-09-15 17:52:20.636
637,3085,355030812A,3550308,Luz,SÃO PAULO,SP,-23.531015,-46.632533,0.0,11,...,NaN,NaN,NaN,2013-12-20 17:10:56.701,2013-12-20 17:10:56.701,2026-09-15 11:10:27,2026-06-16 07:12:44.389,"{'uf': 'SP', 'nome': 'Luz', 'cidade': 'SÃO PAU...",2026-08-28 18:18:21.410,2026-09-15 17:52:22.712
638,3635,355030802A,3550308,COHAB Inácio Monteiro,SÃO PAULO,SP,-23.569000,-46.411000,0.0,11,...,NaN,NaN,NaN,2013-10-29 12:04:44.137,2013-10-29 12:04:44.137,2026-09-14 15:00:25,2026-09-14 17:02:56.803,"{'uf': 'SP', 'nome': 'COHAB Inácio Monteiro', ...",2026-08-28 18:18:23.498,2026-09-15 17:52:24.795
689,3235,355030843A,3550308,Jardim Santa Lucrécia,SÃO PAULO,SP,-23.436000,-46.751000,0.0,11,...,NaN,NaN,NaN,2013-10-10 13:00:53.092,2013-10-10 13:00:53.092,2023-05-02 11:50:31,2023-05-02 13:52:00.124,"{'uf': 'SP', 'nome': 'Jardim Santa Lucrécia', ...",2026-08-28 18:18:17.248,2026-09-15 17:52:18.552
690,3095,355030834A,3550308,Santo Amaro Paulista,SÃO PAULO,SP,-23.650398,-46.708183,0.0,11,...,NaN,NaN,NaN,2013-12-04 14:47:13.419,2013-12-04 14:47:13.419,2026-09-12 17:01:23,2026-09-12 19:08:04.155,"{'uf': 'SP', 'nome': 'Santo Amaro Paulista', '...",2026-08-28 18:18:17.668,2026-09-15 17:52:18.971

In [6]:
df_sp[['cota_alerta', 'cota_atencao', 'cota_transbordamento']].isna().sum()

cota_alerta             79
cota_atencao            79
cota_transbordamento    79
dtype: int64

In [ ]:
  # Drop unnecessary columns
df_sp.drop(columns=['cota_alerta', 'cota_atencao', 'cota_transbordamento', 'raw_payload']).reset_index(drop=True)

,id_estacao,station_code,ibge_code,name,city,state,latitude,longitude,altitude,network_id,network_acronym,station_type_id,station_type_description,installation_date,registration_date,last_transmission,inactive_since,collected_at,updated_at
0,3830,355030899A,3550308,Jardim Eledy,SÃO PAULO,SP,-23.649000,-46.786000,0.0,11,CEMADEN,1,Pluviométrica,2013-11-14 14:18:51.509,2013-11-14 14:18:51.509,2024-06-04 01:50:33,2024-06-04 03:54:15.996,2026-08-28 18:18:07.657,2026-09-15 17:52:08.879
1,3829,355030898A,3550308,Jardim Romano,SÃO PAULO,SP,-23.478880,-46.381210,0.0,11,CEMADEN,1,Pluviométrica,2014-12-02 20:31:16.994,2014-12-02 20:31:16.994,2026-09-15 11:50:38,2026-09-02 16:51:33.056,2026-08-28 18:18:07.863,2026-09-15 17:52:09.088
2,3828,355030897A,3550308,Jaguaré,SÃO PAULO,SP,-23.550000,-46.743000,0.0,11,CEMADEN,1,Pluviométrica,2013-11-08 13:21:13.032,2013-11-08 13:21:13.032,2026-09-15 11:40:29,2026-03-07 05:50:27.726,2026-08-28 18:18:08.070,2026-09-15 17:52:09.299
3,3827,355030896A,3550308,Jardim João XXIII,SÃO PAULO,SP,-23.600000,-46.789000,0.0,11,CEMADEN,1,Pluviométrica,2013-11-12 11:27:25.428,2013-11-12 11:27:25.428,2026-09-15 11:55:47,2026-06-09 16:32:30.437,2026-08-28 18:18:08.284,2026-09-15 17:52:09.507
4,3826,355030895A,3550308,Pirajussara,SÃO PAULO,SP,-23.638000,-46.780000,0.0,11,CEMADEN,1,Pluviométrica,2013-11-07 17:16:18.954,2013-11-07 17:16:18.954,2026-09-14 14:33:16,2026-09-14 16:38:22.561,2026-08-28 18:18:08.490,2026-09-15 17:52:09.714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,4399,355030822B,3550308,Avenida Oratório,SÃO PAULO,SP,-23.613000,-46.523000,0.0,11,CEMADEN,1,Pluviométrica,2013-12-16 13:23:27.225,2013-12-16 13:23:27.225,2026-09-15 07:20:25,2026-09-15 09:25:53.503,2026-08-28 18:18:19.334,2026-09-15 17:52:20.636
75,3085,355030812A,3550308,Luz,SÃO PAULO,SP,-23.531015,-46.632533,0.0,11,CEMADEN,1,Pluviométrica,2013-12-20 17:10:56.701,2013-12-20 17:10:56.701,2026-09-15 11:10:27,2026-06-16 07:12:44.389,2026-08-28 18:18:21.410,2026-09-15 17:52:22.712
76,3635,355030802A,3550308,COHAB Inácio Monteiro,SÃO PAULO,SP,-23.569000,-46.411000,0.0,11,CEMADEN,1,Pluviométrica,2013-10-29 12:04:44.137,2013-10-29 12:04:44.137,2026-09-14 15:00:25,2026-09-14 17:02:56.803,2026-08-28 18:18:23.498,2026-09-15 17:52:24.795
77,3235,355030843A,3550308,Jardim Santa Lucrécia,SÃO PAULO,SP,-23.436000,-46.751000,0.0,11,CEMADEN,1,Pluviométrica,2013-10-10 13:00:53.092,2013-10-10 13:00:53.092,2023-05-02 11:50:31,2023-05-02 13:52:00.124,2026-08-28 18:18:17.248,2026-09-15 17:52:18.552
78,3095,355030834A,3550308,Santo Amaro Paulista,SÃO PAULO,SP,-23.650398,-46.708183,0.0,11,CEMADEN,1,Pluviométrica,2013-12-04 14:47:13.419,2013-12-04 14:47:13.419,2026-09-12 17:01:23,2026-09-12 19:08:04.155,2026-08-28 18:18:17.668,2026-09-15 17:52:18.971

In [8]:
# Classificacao por zona usando zonas_sp.geojson (Centro, Norte, Sul, Leste, Oeste)
import geopandas as gpd

zonas = gpd.read_file(os.path.join(RAIZ, "zonas_sp.geojson"))

# Expande as zonas em 100 m (EPSG:31983) para incluir Cidade Tiradentes 2 (~34 m fora da Leste)
zonas["geometry"] = zonas.to_crs("EPSG:31983").geometry.buffer(40).to_crs("EPSG:4326").geometry

gdf = gpd.GeoDataFrame(
    df_sp,
    geometry=gpd.points_from_xy(df_sp["longitude"], df_sp["latitude"]),
    crs="EPSG:4326",
)
gdf = gpd.sjoin(gdf, zonas, how="left", predicate="within")
gdf["zona"] = gdf["zona"].fillna("Fora de SP")

df_zona = gdf.drop(columns=["geometry", "index_right"]).copy()
print(df_zona["zona"].value_counts())

zona
Leste     28
Sul       27
Norte     14
Oeste      7
Centro     3
Name: count, dtype: int64

In [9]:
df_cemaden_station = df_zona[["id_estacao","station_code","ibge_code", "name", "city","latitude","longitude", "zona",
                             "network_id", "network_acronym","station_type_id","station_type_description","installation_date",
                             "registration_date","last_transmission","inactive_since","collected_at"]].copy()

In [10]:
df_cemaden_station['installation_date'] = pd.to_datetime(df_cemaden_station['installation_date']).dt.date
df_cemaden_station['registration_date'] = pd.to_datetime(df_cemaden_station['registration_date']).dt.date
df_cemaden_station['last_transmission'] = pd.to_datetime(df_cemaden_station['last_transmission']).dt.date
df_cemaden_station['inactive_since'] = pd.to_datetime(df_cemaden_station['inactive_since']).dt.date
df_cemaden_station['collected_at'] = pd.to_datetime(df_cemaden_station['collected_at']).dt.date

df_cemaden_station.head()

,id_estacao,station_code,ibge_code,name,city,latitude,longitude,zona,network_id,network_acronym,station_type_id,station_type_description,installation_date,registration_date,last_transmission,inactive_since,collected_at
79,3830,355030899A,3550308,Jardim Eledy,SÃO PAULO,-23.64900,-46.78600,Sul,11,CEMADEN,1,Pluviométrica,2013-11-14,2013-11-14,2024-06-04,2024-06-04,2026-08-28
80,3829,355030898A,3550308,Jardim Romano,SÃO PAULO,-23.47888,-46.38121,Leste,11,CEMADEN,1,Pluviométrica,2014-12-02,2014-12-02,2026-09-15,2026-09-02,2026-08-28
81,3828,355030897A,3550308,Jaguaré,SÃO PAULO,-23.55000,-46.74300,Oeste,11,CEMADEN,1,Pluviométrica,2013-11-08,2013-11-08,2026-09-15,2026-03-07,2026-08-28
82,3827,355030896A,3550308,Jardim João XXIII,SÃO PAULO,-23.60000,-46.78900,Oeste,11,CEMADEN,1,Pluviométrica,2013-11-12,2013-11-12,2026-09-15,2026-06-09,2026-08-28
83,3826,355030895A,3550308,Pirajussara,SÃO PAULO,-23.63800,-46.78000,Sul,11,CEMADEN,1,Pluviométrica,2013-11-07,2013-11-07,2026-09-14,2026-09-14,2026-08-28

In [19]:
# Mapa das estacoes com pinos coloridos por zona (Icon)
import folium

cores = {
    "Centro": "gray",
    "Norte": "darkblue",
    "Sul": "darkgreen",
    "Leste": "red",
    "Oeste": "darkred",
    "Fora de SP": "lightgray",
}

m = folium.Map(
    location=[df_sp["latitude"].mean(), df_sp["longitude"].mean()],
    zoom_start=12,
)

folium.TileLayer(
    tiles="https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}",
    attr="Google",
    name="Google Maps",
).add_to(m)

for _, r in df_cemaden_station.iterrows():
    cor = cores.get(r["zona"], "gray")
    folium.Marker(
        location=[r["latitude"], r["longitude"]],
        popup=f"{r['name']} - {r['zona']}",
        tooltip=r["name"],
        icon=folium.Icon(color=cor),
    ).add_to(m)

CAMINHO = os.path.join(RAIZ, "cemaden_stations_map.html")
m.save(CAMINHO)
print("Mapa salvo em:", CAMINHO)
m

Mapa salvo em: C:\TI\Projetos Univesp\Projeto - 4\cemaden_stations_map.html

In [12]:
df_cemaden_station['status'] = df_cemaden_station.apply(
    lambda r: 'ativo' if r['last_transmission'] > r['inactive_since'] else 'inativa',
    axis=1
)

df_cemaden_station['status'].value_counts()

status
ativo      51
inativa    28
Name: count, dtype: int64

In [13]:
# opencode -s ses_f5ebfe34fffe48PlZMBhyz8Oqz

In [14]:
df_station = df_cemaden_station.copy()

df_station['installation_date'] = pd.to_datetime(df_station['installation_date']).dt.normalize()
df_station['last_transmission'] = pd.to_datetime(df_station['last_transmission']).dt.normalize()
df_station['inactive_since'] = pd.to_datetime(df_station['inactive_since']).dt.normalize()

today = pd.Timestamp.now().normalize()

df_station['dias_inativa'] = (today - df_station['last_transmission']).dt.days
df_station['anos_inativa'] = (df_station['dias_inativa'] / 365.25).round(1)

df_station.head(10)

,id_estacao,station_code,ibge_code,name,city,latitude,longitude,zona,network_id,network_acronym,station_type_id,station_type_description,installation_date,registration_date,last_transmission,inactive_since,collected_at,status,dias_inativa,anos_inativa
79,3830,355030899A,3550308,Jardim Eledy,SÃO PAULO,-23.64900,-46.78600,Sul,11,CEMADEN,1,Pluviométrica,2013-11-14,2013-11-14,2024-06-04,2024-06-04,2026-08-28,inativa,837,2.3
80,3829,355030898A,3550308,Jardim Romano,SÃO PAULO,-23.47888,-46.38121,Leste,11,CEMADEN,1,Pluviométrica,2014-12-02,2014-12-02,2026-09-15,2026-09-02,2026-08-28,ativo,4,0.0
81,3828,355030897A,3550308,Jaguaré,SÃO PAULO,-23.55000,-46.74300,Oeste,11,CEMADEN,1,Pluviométrica,2013-11-08,2013-11-08,2026-09-15,2026-03-07,2026-08-28,ativo,4,0.0
82,3827,355030896A,3550308,Jardim João XXIII,SÃO PAULO,-23.60000,-46.78900,Oeste,11,CEMADEN,1,Pluviométrica,2013-11-12,2013-11-12,2026-09-15,2026-06-09,2026-08-28,ativo,4,0.0
83,3826,355030895A,3550308,Pirajussara,SÃO PAULO,-23.63800,-46.78000,Sul,11,CEMADEN,1,Pluviométrica,2013-11-07,2013-11-07,2026-09-14,2026-09-14,2026-08-28,inativa,5,0.0
84,3825,355030894A,3550308,Parque Morumbi,SÃO PAULO,-23.62300,-46.72700,Sul,11,CEMADEN,1,Pluviométrica,2013-11-07,2013-11-07,2026-09-15,2026-09-10,2026-08-28,ativo,4,0.0
86,3677,355030885A,3550308,Jardim Anhanguera,SÃO PAULO,-23.44000,-46.78800,Norte,11,CEMADEN,1,Pluviométrica,2013-11-01,2013-11-01,2025-12-18,2025-12-18,2026-08-28,inativa,275,0.8
87,3676,355030884A,3550308,Lajeado,SÃO PAULO,-23.54500,-46.40100,Leste,11,CEMADEN,1,Pluviométrica,2013-11-01,2013-11-01,2026-09-14,2026-09-14,2026-08-28,inativa,5,0.0
88,3617,355030881A,3550308,Itaim Paulista,SÃO PAULO,-23.49400,-46.41700,Leste,11,CEMADEN,1,Pluviométrica,2013-10-29,2013-10-29,2026-09-15,2026-09-02,2026-08-28,ativo,4,0.0
89,3675,355030880A,3550308,Iguatemi,SÃO PAULO,-23.60900,-46.42700,Leste,11,CEMADEN,1,Pluviométrica,2013-11-01,2013-11-01,2026-09-15,2026-06-11,2026-08-28,ativo,4,0.0

In [15]:
df_station['dias_entre_inativacao_e_transmissao'] = (
    df_station['last_transmission'] - df_station['inactive_since']
).dt.days

df_station[['name', 'zona', 'inactive_since', 'last_transmission',
            'dias_entre_inativacao_e_transmissao']].head(5)

,name,zona,inactive_since,last_transmission,dias_entre_inativacao_e_transmissao
79,Jardim Eledy,Sul,2024-06-04,2024-06-04,0
80,Jardim Romano,Leste,2026-09-02,2026-09-15,13
81,Jaguaré,Oeste,2026-03-07,2026-09-15,192
82,Jardim João XXIII,Oeste,2026-06-09,2026-09-15,98
83,Pirajussara,Sul,2026-09-14,2026-09-14,0

In [16]:
group_zona = (
    df_cemaden_station
    .groupby('zona')
    .agg(
        qtd_estacoes=('id_estacao', 'count'),
        ativas=('status', lambda x: (x == 'ativo').sum()),
        inativas=('status', lambda x: (x == 'inativa').sum()),
    )
    .sort_values('qtd_estacoes', ascending=False)
)

group_zona['pct_ativas'] = (group_zona['ativas'] / group_zona['qtd_estacoes'] * 100).round(1)
group_zona['pct_inativas'] = (group_zona['inativas'] / group_zona['qtd_estacoes'] * 100).round(1)

group_zona

        qtd_estacoes  ativas  inativas  pct_ativas  pct_inativas
zona
Leste             28      16        12        57.1          42.9
Sul               27      18         9        66.7          33.3
Norte             14       9         5        64.3          35.7
Oeste              7       6         1        85.7          14.3
Centro             3       2         1        66.7          33.3

In [17]:
import plotly.express as px

# Preparar os dados para o gráfico
dados_grafico = (
    df_station
    .groupby(['zona', 'status'])
    .size()
    .reset_index(name='quantidade')
)

# Ordenar zonas por total
ordem = df_station['zona'].value_counts().index.tolist()

fig = px.bar(
    dados_grafico,
    x='zona',
    y='quantidade',
    color='status',
    category_orders={'zona': ordem, 'status': ['reativada', 'inativa']},
    color_discrete_map={'reativada': '#2ca02c', 'inativa': '#d62728'},
    title='Estações CEMADEN em SP: reativadas vs inativas por zona',
    labels={'quantidade': 'Nº de estações', 'zona': 'Zona', 'status': 'Status'},
    text='quantidade',
)

fig.update_traces(textposition='inside')
fig.update_layout(
    height=500,
    legend_title_text='Status',
    xaxis_title='Zona',
    yaxis_title='Número de estações',
)

fig.show()

In [18]:
import folium

m = folium.Map(
    location=[df_station['latitude'].mean(), df_station['longitude'].mean()],
    zoom_start=12,
)

cores = {
    'ativo': 'green',
    'inativa': 'red',
}

for _, r in df_station.iterrows():
    folium.Marker(
        location=[r['latitude'], r['longitude']],
        popup=(
            f"<b>{r['name']}</b><br>"
            f"Zona: {r['zona']}<br>"
            f"Status: {r['status']}<br>"
            f"Última transmissão: {r['last_transmission'].strftime('%d/%m/%Y')}<br>"
            f"Inativa desde: {r['inactive_since'].strftime('%d/%m/%Y')}"
        ),
        tooltip=f"{r['name']} ({r['status']})",
        icon=folium.Icon(color=cores[r['status']], icon='info-sign'),
    ).add_to(m)

m

In [24]:
df_reading = pd.read_sql("SELECT * FROM cemaden_reading", engine)
df_sensor  = pd.read_sql("SELECT * FROM cemaden_sensor", engine)

print(f"Leituras:  {len(df_reading)}")
print(f"Estações:  {len(df_station)}")
print(f"Sensores:  {len(df_sensor)}")

Leituras:  8174
Estações:  79
Sensores:  48

In [25]:
df_reading["observation_date"] = pd.to_datetime(df_reading["observation_date"])

print("Período das leituras:")
print(f"  De:  {df_reading['observation_date'].min()}")
print(f"  Até: {df_reading['observation_date'].max()}")
print(f"  Dias distintos: {df_reading['observation_date'].dt.date.nunique()}")

Período das leituras:
  De:  2026-08-28 15:50:00
  Até: 2026-09-15 18:50:00
  Dias distintos: 2

In [26]:
# Contar leituras por sensor_id
leituras_por_sensor = (
    df_reading
    .groupby("sensor_id")
    .size()
    .reset_index(name="qtd_leituras")
    .sort_values("qtd_leituras", ascending=False)
)

# Juntar com a descrição do sensor
leituras_por_sensor = leituras_por_sensor.merge(
    df_sensor[["id", "description"]],
    left_on="sensor_id",
    right_on="id",
    how="left"
)

leituras_por_sensor[["sensor_id", "description", "qtd_leituras"]]

    sensor_id                  description  qtd_leituras
0          10                        Chuva          3532
1         240  Intensidade da Precipitação          3530
2         340      Umidade do Solo Nível 2           175
3         350      Umidade do Solo Nível 3           169
4         610      Umidade do Solo Nível 5           169
5         620      Umidade do Solo Nível 6           169
6         360      Umidade do Solo Nível 4           149
7          20                        Nível            72
8         260                 Nível Mínimo            72
9         270                 Nível Máximo            72
10        330      Umidade do Solo Nível 1            65

In [27]:
# 1. Juntar leitura com estação (pelo station_code)
# 2. Juntar com sensor (pelo sensor_id)

df_full = (
    df_reading
    .merge(
        df_station[["station_code", "name", "city", "zona",
                    "latitude", "longitude"]],
        on="station_code",
        how="left"
    )
    .merge(
        df_sensor[["id", "description"]],
        left_on="sensor_id",
        right_on="id",
        how="left",
        suffixes=("", "_sensor")
    )
)

print(f"Total de linhas após merge: {len(df_full)}")
print(f"Colunas: {df_full.columns.tolist()}")
print()
df_full.head()

Total de linhas após merge: 8174
Colunas: ['id', 'station_code', 'sensor_id', 'observation_date', 'value', 'qualification', 'raw_payload', 'collected_at', 'name', 'city', 'zona', 'latitude', 'longitude', 'id_sensor', 'description']

,id,station_code,sensor_id,observation_date,value,qualification,raw_payload,collected_at,name,city,zona,latitude,longitude,id_sensor,description
0,1,354820301A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Centro', 'valor': 0, 'ci...",2026-08-28 18:44:49.627,NaN,NaN,NaN,NaN,NaN,240,Intensidade da Precipitação
1,2,350450302A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Centro', 'valor': 0, 'ci...",2026-08-28 18:44:51.034,NaN,NaN,NaN,NaN,NaN,240,Intensidade da Precipitação
2,3,353180301A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Santa Cruz', 'valor': 0,...",2026-08-28 18:44:51.246,NaN,NaN,NaN,NaN,NaN,240,Intensidade da Precipitação
3,4,353440103A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Rochdale', 'valor': 0, '...",2026-08-28 18:44:51.456,NaN,NaN,NaN,NaN,NaN,240,Intensidade da Precipitação
4,5,355240301A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Vila Miranda', 'valor': ...",2026-08-28 18:44:51.665,NaN,NaN,NaN,NaN,NaN,240,Intensidade da Precipitação