# Análise exploratória do CEMADEN para São Paulo

## Objetivo
Este notebook reúne a etapa inicial de exploração do conjunto de dados do CEMADEN, com foco em:
- carga e integração das tabelas de leitura, estação e sensor;
- validação básica da qualidade dos dados;
- análise espacial por zona da cidade;
- avaliação do comportamento de precipitação e do status das estações.

## Estratégia de análise
1. Carregar as tabelas do banco;
2. validar chaves e campos essenciais;
3. filtrar os dados de São Paulo;
4. enriquecer com zona geográfica e status das estações;
5. verificar qualidade, distribuições e padrões temporais.

> A análise abaixo foi organizada para dar suporte ao entendimento do dado antes de formular conclusões finais do projeto.

In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine, inspect

RAIZ = r"C:\TI\Projetos Univesp\Projeto - 4"

In [2]:
dadosUrl = "postgresql://noaa_user:C53AONMRWKIZ3nlrVkQPpGMVmWjNNpyu@dpg-da6a5oqjnfac73aajj5g-a.oregon-postgres.render.com/noaa?sslmode=require"

In [3]:
engine = create_engine(dadosUrl)
inspector = inspect(engine)
print(inspector.get_table_names())

['ana_telemetry_reading', 'cemaden_sensor', 'cemaden_station', 'cemaden_reading', 'noaa_enso_weekly', 'ana_station']

In [4]:
df_reading = pd.read_sql("SELECT * FROM cemaden_reading", engine)
df_station = pd.read_sql("SELECT * FROM cemaden_station", engine)
df_sensor  = pd.read_sql("SELECT * FROM cemaden_sensor", engine)

print(f"Leituras:  {len(df_reading)}")
print(f"Estações:  {len(df_station)}")
print(f"Sensores:  {len(df_sensor)}")

#CAMINHO_READING = os.path.join(RAIZ, "df_reading.xlsx")
#try:
#    import openpyxl
#except ModuleNotFoundError:
#    import subprocess
#    import sys
#    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'openpyxl'])
#    import openpyxl
#CAMINHO_STATION = os.path.join(RAIZ, "df_station.xlsx")
#CAMINHO_SENSOR = os.path.join(RAIZ, "df_sensor.xlsx")

#df_reading.to_excel(CAMINHO_READING, index=False)
#df_station.to_excel(CAMINHO_STATION, index=False)
#df_sensor.to_excel(CAMINHO_SENSOR, index=False)

#print("Arquivos Excel salvos:")
#print(CAMINHO_READING)
#print(CAMINHO_STATION)
#print(CAMINHO_SENSOR)

Leituras:  8174
Estações:  710
Sensores:  48

In [5]:
df_reading.head()

,id,station_code,sensor_id,observation_date,value,qualification,raw_payload,collected_at
0,1,354820301A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Centro', 'valor': 0, 'ci...",2026-08-28 18:44:49.627
1,2,350450302A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Centro', 'valor': 0, 'ci...",2026-08-28 18:44:51.034
2,3,353180301A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Santa Cruz', 'valor': 0,...",2026-08-28 18:44:51.246
3,4,353440103A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Rochdale', 'valor': 0, '...",2026-08-28 18:44:51.456
4,5,355240301A,240,2026-08-28 15:50:00,0.0,0000,"{'uf': 'SP', 'nome': 'Vila Miranda', 'valor': ...",2026-08-28 18:44:51.665

In [6]:
pos = df_reading.columns.get_loc('sensor_id')

for col in ['nome', 'uf', 'latitude', 'longitude']:
    if col in df_reading.columns:
        df_reading = df_reading.drop(columns=[col])

df_reading.insert(pos + 1, 'nome', df_reading['raw_payload'].apply(lambda x: x.get('nome')))
df_reading.insert(pos + 2, 'uf', df_reading['raw_payload'].apply(lambda x: x.get('uf')))
df_reading.insert(pos + 3, 'latitude', df_reading['raw_payload'].apply(lambda x: x.get('latitude')))
df_reading.insert(pos + 4, 'longitude', df_reading['raw_payload'].apply(lambda x: x.get('longitude')))
df_reading.drop(columns=['raw_payload'], inplace=True)      

#print(df_reading['raw_payload'].iloc[0])
df_reading

,id,station_code,sensor_id,nome,uf,latitude,longitude,observation_date,value,qualification,collected_at
0,1,354820301A,240,Centro,SP,-22.83151,-45.66007,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:49.627
1,2,350450302A,240,Centro,SP,-23.10100,-48.92000,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.034
2,3,353180301A,240,Santa Cruz,SP,-22.90500,-47.34300,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.246
3,4,353440103A,240,Rochdale,SP,-23.50700,-46.77600,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.456
4,5,355240301A,240,Vila Miranda,SP,-22.82600,-47.27700,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.665
...,...,...,...,...,...,...,...,...,...,...,...
8169,9649,352610001A,240,Vila Florindo,SP,-24.31700,-47.64100,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:37.588
8170,9650,352590405A,240,Roseira,SP,-23.14300,-46.81800,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:37.796
8171,9653,352400603A,10,Parque dos Cafezais,SP,-23.18500,-47.10500,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:38.002
8172,9655,352610001A,10,Vila Florindo,SP,-24.31700,-47.64100,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:38.242
8173,9656,355030851A,10,Jaraguá,SP,-23.48000,-46.76200,2026-09-15 18:50:00,0.0,0000,2026-09-15 17:51:38.543

In [10]:
df_sensor.head(5)

,id,description,collected_at,updated_at
0,430,Direção do Vento Predominante - Diária,2026-08-28 18:17:43.617,2026-09-15 17:51:44.976
1,440,Temperatura do Solo Nível 1 Máxima - Diária,2026-08-28 18:17:43.822,2026-09-15 17:51:45.179
2,450,Temperatura do Solo Nível 1 Mínima - Diária,2026-08-28 18:17:44.026,2026-09-15 17:51:45.384
3,460,Temperatura do Solo Nível 2 Máxima - Diária,2026-08-28 18:17:44.230,2026-09-15 17:51:45.587
4,470,Temperatura do Solo Nível 2 Mínima - Diária,2026-08-28 18:17:44.433,2026-09-15 17:51:45.791

In [11]:
df_reading['sensor_id'] = df_reading['sensor_id'].astype(str).str.strip()
df_sensor['id'] = df_sensor['id'].astype(str).str.strip()
match = df_reading['sensor_id'].isin(df_sensor['id'])
print(f"Casam: {match.sum()} de {len(df_reading)} linhas")

Casam: 8174 de 8174 linhas

In [27]:
df_cemaden = df_reading.merge(
    df_sensor, left_on='sensor_id',
    right_on='id', how='left',
    validate='many_to_one',
    suffixes=('_reading', '_sensor')
)

cols = df_cemaden.columns.tolist()
cols.remove('description')
pos = cols.index('longitude') + 1
cols.insert(pos, 'description')
df_cemaden = df_cemaden[cols]

df_cemaden.drop(columns=['id_sensor', 'collected_at_sensor'], inplace=True)
df_cemaden.rename(columns={'id_reading': 'id', 'collected_at_reading': 'collected_at'}, inplace=True)
df_cemaden

,id,station_code,sensor_id,nome,uf,latitude,longitude,description,observation_date,value,qualification,collected_at,updated_at
0,1,354820301A,240,Centro,SP,-22.83151,-45.66007,Intensidade da Precipitação,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:49.627,2026-09-15 17:51:39.238
1,2,350450302A,240,Centro,SP,-23.10100,-48.92000,Intensidade da Precipitação,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.034,2026-09-15 17:51:39.238
2,3,353180301A,240,Santa Cruz,SP,-22.90500,-47.34300,Intensidade da Precipitação,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.246,2026-09-15 17:51:39.238
3,4,353440103A,240,Rochdale,SP,-23.50700,-46.77600,Intensidade da Precipitação,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.456,2026-09-15 17:51:39.238
4,5,355240301A,240,Vila Miranda,SP,-22.82600,-47.27700,Intensidade da Precipitação,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.665,2026-09-15 17:51:39.238
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8169,9649,352610001A,240,Vila Florindo,SP,-24.31700,-47.64100,Intensidade da Precipitação,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:37.588,2026-09-15 17:51:39.238
8170,9650,352590405A,240,Roseira,SP,-23.14300,-46.81800,Intensidade da Precipitação,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:37.796,2026-09-15 17:51:39.238
8171,9653,352400603A,10,Parque dos Cafezais,SP,-23.18500,-47.10500,Chuva,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:38.002,2026-09-15 17:51:39.033
8172,9655,352610001A,10,Vila Florindo,SP,-24.31700,-47.64100,Chuva,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:38.242,2026-09-15 17:51:39.033
8173,9656,355030851A,10,Jaraguá,SP,-23.48000,-46.76200,Chuva,2026-09-15 18:50:00,0.0,0000,2026-09-15 17:51:38.543,2026-09-15 17:51:39.033

In [13]:
print("Linhas:", len(df_cemaden))
print("id max:", df_cemaden['id_reading'].max())
print("ids únicos:", df_cemaden['id_reading'].nunique())
print("Faltam ids (gaps):", df_cemaden['id_reading'].max() - df_cemaden['id_reading'].nunique() + 1)

Linhas: 8174
id max: 9656
ids únicos: 8174
Faltam ids (gaps): 1483

In [15]:
df_station.head(5)

,id_estacao,station_code,ibge_code,name,city,state,latitude,longitude,altitude,network_id,...,cota_alerta,cota_atencao,cota_transbordamento,installation_date,registration_date,last_transmission,inactive_since,raw_payload,collected_at,updated_at
0,7709,355670101A,3556701,Centro,VINHEDO,SP,-23.02933,-46.982518,0.0,11,...,NaN,NaN,NaN,2015-05-07 17:12:10.815,2015-05-07 17:12:10.815,2026-09-15 11:22:24,2025-12-31 06:20:35.174,"{'uf': 'SP', 'nome': 'Centro', 'cidade': 'VINH...",2026-08-28 18:17:48.301,2026-09-15 17:51:49.576
1,4410,355650301A,3556503,COMDEC,VÁRZEA PAULISTA,SP,-23.21100,-46.832000,0.0,11,...,NaN,NaN,NaN,2013-12-23 00:00:00.000,2013-12-23 12:24:12.341,2026-09-15 11:40:26,2025-12-31 06:40:37.267,"{'uf': 'SP', 'nome': 'COMDEC', 'cidade': 'VÁRZ...",2026-08-28 18:17:48.727,2026-09-15 17:51:49.990
2,6447,355645301A,3556453,Jardim Betânia,VARGEM GRANDE PAULISTA,SP,-23.60200,-47.021000,0.0,11,...,NaN,NaN,NaN,2014-08-18 14:42:37.915,2014-08-18 14:42:37.915,2026-09-10 20:40:28,2026-09-10 22:41:32.481,"{'uf': 'SP', 'nome': 'Jardim Betânia', 'cidade...",2026-08-28 18:17:48.937,2026-09-15 17:51:50.199
3,8674,355640401A,3556404,Centro,VARGEM GRANDE DO SUL,SP,-21.82982,-46.895090,0.0,11,...,NaN,NaN,NaN,2015-11-11 18:59:29.943,2015-11-11 18:59:29.943,2024-06-23 13:50:15,2024-06-23 15:51:05.991,"{'uf': 'SP', 'nome': 'Centro', 'cidade': 'VARG...",2026-08-28 18:17:49.354,2026-09-15 17:51:50.617
4,6316,355635401A,3556354,SP036,VARGEM,SP,-22.89800,-46.380000,0.0,11,...,NaN,NaN,NaN,2014-04-25 11:50:40.723,2014-04-25 11:50:40.723,2024-11-23 10:50:51,2024-11-23 12:54:03.850,"{'uf': 'SP', 'nome': 'SP036', 'cidade': 'VARGE...",2026-08-28 18:17:49.561,2026-09-15 17:51:50.827

In [16]:
print(df_station['raw_payload'].iloc[0])

{'uf': 'SP', 'nome': 'Centro', 'cidade': 'VINHEDO', 'offset': None, 'codibge': 3556701, 'id_rede': 11, 'altitude': 0, 'latitude': -23.02933, 'longitude': -46.982518, 'codestacao': '355670101A', 'id_estacao': 7709, 'rede_sigla': 'CEMADEN', 'cota_alerta': None, 'dh_cadastro': '2015-05-07 17:12:10.815', 'cota_atencao': None, 'id_tipoestacao': 1, 'data_instalacao': '2015-05-07 17:12:10.815', 'dh_inicio_inativo': '2025-12-31 06:20:35.174', 'dh_ultima_remessa': '2026-09-15 11:22:24.000', 'cota_transbordamento': None, 'tipoestacao_descricao': 'Pluviométrica'}

In [17]:
existentes = df_reading['station_code'].isin(df_station['station_code'])
print(f"{existentes.sum()} de {len(df_reading)} linhas")

8174 de 8174 linhas

In [18]:
nao_cadastradas = set(df_reading['station_code']) - set(df_station['station_code'])
print("Leituras com estação não cadastrada:", nao_cadastradas)

Leituras com estação não cadastrada: set()

In [19]:
print("Estaçoes com pelo menos 1 leitura:", df_reading['station_code'].nunique())
print("Total de estaçoes cadastradas:", df_station['station_code'].nunique())
print("Estações sem leitura:", df_station['station_code'].nunique() - df_reading['station_code'].nunique())
print(set(df_reading['station_code']) <= set(df_station['station_code']))

Estaçoes com pelo menos 1 leitura: 498
Total de estaçoes cadastradas: 710
Estações sem leitura: 212
True

In [20]:
df_station['station_type_description'].value_counts()
#df_station.isna().sum()
#print(df_station['raw_payload'].iloc[0])

station_type_description
Pluviométrica    646
Geotécnica        35
Hidrológica       28
Acqua              1
Name: count, dtype: int64

In [26]:
df_cemaden = df_cemaden.merge(
    df_station[['station_code', 'station_type_description']],
    on='station_code',
    how='left',
    validate='many_to_one',
    suffixes=('_reading', '_station')
)

colunas = df_cemaden.columns.tolist()
colunas.remove('station_type_description')
colunas.insert(colunas.index('description') + 1, 'station_type_description')
df_cemaden = df_cemaden[colunas]
df_cemaden.to_csv(os.path.join(RAIZ, "docs/cemaden.csv"), index=False)

df_cemaden.to_csv(os.path.join(RAIZ, "docs/cemaden.csv"), index=False)

df_cemaden

,id_reading,station_code,sensor_id,nome,uf,latitude,longitude,description,station_type_description,observation_date,value,qualification,collected_at_reading,id_sensor,collected_at_sensor,updated_at
0,1,354820301A,240,Centro,SP,-22.83151,-45.66007,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:49.627,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
1,2,350450302A,240,Centro,SP,-23.10100,-48.92000,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.034,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
2,3,353180301A,240,Santa Cruz,SP,-22.90500,-47.34300,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.246,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
3,4,353440103A,240,Rochdale,SP,-23.50700,-46.77600,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.456,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
4,5,355240301A,240,Vila Miranda,SP,-22.82600,-47.27700,Intensidade da Precipitação,Pluviométrica,2026-08-28 15:50:00,0.0,0000,2026-08-28 18:44:51.665,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8169,9649,352610001A,240,Vila Florindo,SP,-24.31700,-47.64100,Intensidade da Precipitação,Pluviométrica,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:37.588,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
8170,9650,352590405A,240,Roseira,SP,-23.14300,-46.81800,Intensidade da Precipitação,Pluviométrica,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:37.796,240,2026-08-28 18:17:37.851,2026-09-15 17:51:39.238
8171,9653,352400603A,10,Parque dos Cafezais,SP,-23.18500,-47.10500,Chuva,Pluviométrica,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:38.002,10,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033
8172,9655,352610001A,10,Vila Florindo,SP,-24.31700,-47.64100,Chuva,Pluviométrica,2026-09-15 18:20:00,0.0,0000,2026-09-15 17:51:38.242,10,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033
8173,9656,355030851A,10,Jaraguá,SP,-23.48000,-46.76200,Chuva,Pluviométrica,2026-09-15 18:50:00,0.0,0000,2026-09-15 17:51:38.543,10,2026-08-28 18:17:36.456,2026-09-15 17:51:39.033

In [23]:
stations_com_leitura = set(df_cemaden["station_code"])
df_cemaden["tem_leitura"] = df_cemaden["station_code"].isin(stations_com_leitura)
print(df_cemaden["tem_leitura"].value_counts())

tem_leitura
True    8174
Name: count, dtype: int64

In [ ]:
import folium

m = folium.Map(
    location=[df_cemaden["latitude"].mean(), df_cemaden["longitude"].mean()],
    zoom_start=12,
)

folium.TileLayer(
    tiles="https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}",
    attr="Google",
    name="Google Maps",
).add_to(m)

for _, r in df_cemaden.iterrows():
    cor = "blue" if r["tem_leitura"] else "red"
    status = "CADASTRADA (com leitura)" if r["tem_leitura"] else "SEM leitura"
    folium.Marker(
        location=[r["latitude"], r["longitude"]],
        popup=f"{r['name']} - {status}",
        tooltip=f"{r['name']} ({status})",
        icon=folium.Icon(color=cor),
    ).add_to(m)

from folium.plugins import FeatureGroupSubGroup, GroupedLayerControl

grupo_azul = folium.FeatureGroup(name="Com leitura (azul)")
grupo_vermelho = folium.FeatureGroup(name="Sem leitura (vermelho)")

CAMINHO = os.path.join(RAIZ, "cemaden_stations_map.html")
m.save(CAMINHO)
print("Mapa salvo em:", CAMINHO)
m

In [94]:
import geopandas as gpd

zonas = gpd.read_file(os.path.join(RAIZ, "zonas_sp.geojson"))

# Expande as zonas em 100 m (EPSG:31983) para incluir Cidade Tiradentes 2 (~34 m fora da Leste)
zonas["geometry"] = zonas.to_crs("EPSG:31983").geometry.buffer(40).to_crs("EPSG:4326").geometry

gdf = gpd.GeoDataFrame(
    df_station,
    geometry=gpd.points_from_xy(df_station["longitude"], df_station["latitude"]),
    crs="EPSG:4326",
)
gdf = gpd.sjoin(gdf, zonas, how="left", predicate="within")
gdf["zona"] = gdf["zona"].fillna("Fora de SP")

df_station_sp = gdf.drop(columns=["geometry", "index_right"]).copy()
print(df_station_sp["zona"].value_counts())

zona
Fora de SP    630
Sul            28
Leste          28
Norte          14
Oeste           7
Centro          3
Name: count, dtype: int64

In [ ]:
# Mapa das estacoes com pinos coloridos por zona (Icon)
import folium

cores = {
    "Centro": "gray",
    "Norte": "darkblue",
    "Sul": "darkgreen",
    "Leste": "red",
    "Oeste": "darkred",
    "Fora de SP": "lightgray",
}

m = folium.Map(
    location=[df_station_sp["latitude"].mean(), df_station_sp["longitude"].mean()],
    zoom_start=12,
)

folium.TileLayer(
    tiles="https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}",
    attr="Google",
    name="Google Maps",
).add_to(m)

for _, r in df_station_sp.iterrows():
    cor = cores.get(r["zona"], "gray")
    folium.Marker(
        location=[r["latitude"], r["longitude"]],
        popup=f"{r['name']} - {r['zona']}",
        tooltip=r["name"],
        icon=folium.Icon(color=cor),
    ).add_to(m)

CAMINHO = os.path.join(RAIZ, "stations_map.html")
m.save(CAMINHO)
print("Mapa salvo em:", CAMINHO)
m