<h2> 1 Análise exploratória dos índices do Pacífico (NOAA) </h2>

## Objetivo
Este notebook explora a série temporal dos índices Niño (1+2, 3, 3.4 e 4) para compreender a variabilidade climática do Pacífico e preparar a base para uso em análises futuras com dados locais do CEMADEN e ANA.

## Estratégia
1. validar a qualidade da base NOAA;
2. padronizar datas e colunas;
3. analisar distribuição, variação, cálculo para identificação dos eventos El-Ninos;
4. preparar a base para ETL e cruzamento posterior com dados regionais.

In [ ]:
# 2 - Importação das bibliotecas

import pandas as pd
import numpy as np
from sqlalchemy import create_engine, inspect

In [ ]:
# 3 - Configuração da conexão com o PostgreSQL
dadosUrl = "postgresql://noaa_user:C53AONMRWKIZ3nlrVkQPpGMVmWjNNpyu@dpg-da6a5oqjnfac73aajj5g-a.oregon-postgres.render.com/noaa?sslmode=require"

In [ ]:
# 4 - Conexão ao banco e listagem das tabelas
engine = create_engine(dadosUrl)
inspector = inspect(engine)  
print(inspector.get_table_names())

In [ ]:
# 5 - Carregamento, validação e preparação dos dados NOAA
df = pd.read_csv(
    "C:/TI/Projetos Univesp/Projeto - 4/docs/noaa_enso_weekly.csv", 
    sep=";", 
    encoding="utf-8",
    decimal=",", 
    index_col=0
)

df["observation_date"] = pd.to_datetime(df["observation_date"], errors="coerce")
df = df.sort_values("observation_date").reset_index(drop=True)

print('Linhas totais:', len(df))
print('Duplicatas por data:', df.duplicated(subset=['observation_date']).sum())
print('Datas nulas:', df['observation_date'].isna().sum())
print('Faixa temporal:', df['observation_date'].min(), 'até', df['observation_date'].max())
print('\nTipos de colunas:')
print(df.dtypes)
print('\nValores nulos por coluna:')
print(df.isna().sum())
print('\nResumo estatístico dos índices:')
print(df[["nino12", "nino3", "nino34", "nino4"]].describe().round(3))

# Se houver colunas geográficas ou complementares, manter como referência

# para a análise final e para o ETL no banco.

#import os

#RAIZ = r"C:\TI\Projetos Univesp\Projeto - 4"


#for col in ['nino12', 'nino3', 'nino34', 'nino4']:

#    df[col] = df[col].astype(float)


#df.to_csv(os.path.join(

#    RAIZ, "docs/noaa_enso_weekly.csv"), 

#    index=False, sep=";", 

#    encoding="utf-8-sig",

#    decimal=",",

#    float_format="%.2f") 

df.head(5)


# ---- CORRECAO: colunas numericas vieram como str (CSV com virgula decimal) ----

# NOAA exporta "0,55" (virgula). pandas le como texto -> precisa converter apos a carga.

cols_num = ["nino12", "nino3", "nino34", "nino4"]

for col in cols_num:

    df[col] = pd.to_numeric(

        df[col].astype(str).str.replace(",", ".", regex=False),

        errors="coerce",

    )

print("Tipos apos conversao:")

print(df.dtypes.to_string())

Linhas totais: 36
Duplicatas por data: 0
Datas nulas: 0
Faixa temporal: 2026-01-07 00:00:00 até 2026-09-09 00:00:00

Tipos de colunas:
observation_date    datetime64[us]
nino12                     float64
nino3                      float64
nino34                     float64
nino4                      float64
collected_at                   str
dtype: object

Valores nulos por coluna:
observation_date    0
nino12              0
nino3               0
nino34              0
nino4               0
collected_at        0
dtype: int64

Resumo estatístico dos índices:
       nino12   nino3  nino34   nino4
count  36.000  36.000  36.000  36.000
mean    1.628   0.722   0.428   0.200
std     1.305   1.168   0.988   0.376
min    -1.000  -1.300  -1.000  -0.500
25%     0.775  -0.325  -0.600  -0.100
50%     1.250   0.550   0.400   0.200
75%     2.725   1.600   1.325   0.500
max     3.900   2.800   2.000   0.800
Tipos apos conversao:
observation_date    datetime64[us]
nino12                     float64
nino3                      float64
nino34                     float64
nino4                      float64
collected_at                   str

In [ ]:
# 6 - Visualização dos dados carregados
df

In [ ]:
# 7 - Descrição geográfica das regiões Niño

regioes_descricao = pd.DataFrame({
    "Região": ["Niño 1+2", "Niño 3", "Niño 3.4", "Niño 4"],

    "Latitude": [
        "0°–10° Sul",
        "5°N–5°S",
        "5°N–5°S",
        "5°N–5°S"
    ],

    "Longitude": [
        "90°W–80°W",
        "150°W–90°W",
        "170°W–120°W",
        "160°E–150°W"
    ],

    "Descrição": [
        "Costa do Peru",
        "Pacífico Leste",
        "Pacífico Centro-Leste (usada para o índice Roni/ONI)",
        "Pacífico Centro-Oeste"
    ],
})

In [ ]:
# ============================================================
# 8 — Distribuição das anomalias semanais por região
# ============================================================

total = len(df)
cols = ["nino12", "nino3", "nino34", "nino4"]
nomes = {"nino12": "Niño 1+2", "nino3": "Niño 3", "nino34": "Niño 3.4", "nino4": "Niño 4"}

linhas = []
for col in cols:
    aquec = (df[col] >= 0.5).sum()
    resfr = (df[col] <= -0.5).sum()
    linhas.append({
        "Região": nomes[col],
        "El Niño (>= 0.5°C)": aquec / total,
        "La Niña (<= -0.5°C)": resfr / total,
        "Neutro (entre ±0.5°C)": (total - aquec - resfr) / total,
    })

print("Resumo do aquecimento e resfriamento por região - Etapa 3:")
print("Total de observações em semanas:", total)
print("-" * 62)
df_media = pd.DataFrame(linhas)

df_media = df_media.merge(
    regioes_descricao,
    on="Região",
    how="left"
)

# Exporta frações numéricas para o Power Query interpretar como porcentagem.
df_media.to_csv(
    "C:/TI/Projetos Univesp/Projeto - 4/docs/media_distribuicao_elnino.csv", 
    sep=";", 
    encoding="utf-8-sig", 
    decimal=",",
    float_format="%.4f",
    index=False
)

# Exibe as mesmas colunas como porcentagens no notebook.
colunas_percentuais = [
    "El Niño (>= 0.5°C)",
    "La Niña (<= -0.5°C)",
    "Neutro (entre ±0.5°C)",
]

df_media.style.format({coluna: "{:.2%}" for coluna in colunas_percentuais})

Resumo do aquecimento e resfriamento por região - Etapa 3:
Total de observações em semanas: 36
--------------------------------------------------------------

In [ ]:
# ============================================================
# 9 — Série temporal mensal das anomalias por região
# ============================================================

import plotly.graph_objects as go

mensal = (
    df.groupby(
        pd.Grouper(key="observation_date", freq="MS")
    )[["nino12", "nino3", "nino34", "nino4"]]
    .mean()
)

nomes = {
    "nino12": "Niño 1+2",
    "nino3": "Niño 3",
    "nino34": "Niño 3.4",
    "nino4": "Niño 4"
}

cores = {
    "nino12": "#c0392b",
    "nino3": "#e67e22",
    "nino34": "#2980b9",
    "nino4": "#27ae60"
}

fig = go.Figure()

# Séries mensais
for col in ["nino12", "nino3", "nino34", "nino4"]:
    fig.add_trace(
        go.Scatter(
            x=mensal.index,
            y=mensal[col],
            name=nomes[col],
            mode="lines+markers",
            line=dict(
                color=cores[col],
                width=2.5
            )
        )
    )

# Linha de referência 0 °C
fig.add_trace(
    go.Scatter(
        x=[mensal.index.min(), mensal.index.max()],
        y=[0, 0],
        mode="lines",
        line=dict(
            color="red",
            width=1.5,
            dash="dash"
        ),
        name=" 0 °C"
    )
)

fig.update_layout(
    title="Evolução mensal das anomalias de TSM — Regiões Niño (2026)",
    xaxis_title="Mês",
    yaxis_title="Anomalia de TSM (°C)",
    template="plotly_white",
    legend_title="Região",
    hovermode="x unified"
)

print("Gráfico de séries temporais — Etapa 4:")

fig.show()

Gráfico de séries temporais — Etapa 4:

<h2>10 - Definição e fonte da anomalia (El Niño / La Niña / Neutro)</h2>

A classificação em El Niño, La Niña e Neutro não é arbitrária — ela segue a
definição operacional da NOAA para o índice ONI (Oceanic Niño Index):

- O **ONI é a média móvel de 3 meses** da anomalia de temperatura da
  superfície do mar (TSM / SST) na região **Niño 3.4 (5°N–5°S, 120°W–170°W)**,
  comparada a uma climatologia de 30 anos (base centrada, atualizada a cada
  5 anos).
- Limiar oficial: anomalia **≥ +0,5 °C ⇒ El Niño**; **≤ −0,5 °C ⇒ La Niña**;
  valores entre os dois ⇒ **Neutro**.
- Para catalogar um evento, a NOAA exige o limiar mantido por **pelo menos
  5 trimestres consecutivos** — uma única semana ou mês acima do limiar não
  caracteriza, por si só, um episódio oficial.
- Em 2026 a NOAA passou a usar o **RONI** (Relative Oceanic Niño Index), com
  os mesmos limiares ±0,5 °C, mas medindo a anomalia do Niño 3.4 em relação à
  anomalia média dos trópicos globais (20°S–20°N).

**Fontes:**
- NOAA Climate.gov — *Climate Variability: Oceanic Niño Index*.
  https://www.climate.gov/news-features/understanding-climate/climate-variability-oceanic-nino-index
- NOAA Climate Prediction Center (CPC) — *Oceanic Niño Index (ONI)*.
  https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso/oni/v6/
- Trenberth, K. E. (1997). *The Definition of El Niño*. Bulletin of the
  American Meteorological Society, 78(12), 2771–2778.

In [ ]:
# ============================================================
# 11 — Cálculo e classificação do RONI/3.4
# ============================================================

df["observation_date"] = pd.to_datetime(df["observation_date"])

# 1) Anomalia mensal do Niño 3.4
mensal = (
    df.groupby(
        pd.Grouper(key="observation_date", freq="MS")
    )[["nino34"]]
    .mean()
)

# 2) RONI/3.4 = média móvel de 3 meses
mensal["RONI"] = (
    mensal["nino34"]
    .rolling(window=3, min_periods=3)
    .mean()
)

# 3) Nome das temporadas de 3 meses
temporadas = {
    3: "JFM",
    4: "FMA",
    5: "MAM",
    6: "AMJ",
    7: "MJJ",
    8: "JJA",
    9: "JAS",
    10: "ASO",
    11: "SON",
    12: "OND"
}

mensal["Temporada"] = mensal.index.month.map(temporadas)

# 4) Classificação da fase
def classificar(valor):
    if pd.isna(valor):
        return "Sem dados"
    elif valor >= 0.5:
        return "El Niño"
    elif valor <= -0.5:
        return "La Niña"
    else:
        return "Neutro"

mensal["Fase"] = mensal["RONI"].apply(classificar)

# 5) DataFrame final da Etapa 1
df_roni = (
    mensal
    .dropna(subset=["RONI"])
    [["Temporada", "RONI", "Fase"]]
    .rename(columns={"RONI": "RONI/3.4"})
    .copy()
)

# ============================================================
# RESULTADO
# ============================================================

print("===== ETAPA 1 — RONI/3.4 (NOAA) =====")

print(
    df_roni
    .round({"RONI/3.4": 2})
    .to_string(index=False)
)

df_roni.to_csv(
    "C:/TI/Projetos Univesp/Projeto - 4/docs/media_movel_34.csv", 
    sep=";", 
    encoding="utf-8-sig", 
    decimal=",", 
    float_format="%.3f",
    index=False
)

print()

ult_temp = df_roni.iloc[-1]

print(f"> Última temporada: {ult_temp['Temporada']}")
print(f"> Último RONI/3.4: {ult_temp['RONI/3.4']:+.3f} °C")
print(f"> Fase: {ult_temp['Fase']}")

===== ETAPA 1 — RONI/3.4 (NOAA) =====
Temporada  RONI/3.4    Fase
      JFM     -0.69 La Niña
      FMA     -0.39  Neutro
      MAM     -0.02  Neutro
      AMJ      0.49  Neutro
      MJJ      0.94 El Niño
      JJA      1.38 El Niño
      JAS      1.68 El Niño

> Última temporada: JAS
> Último RONI/3.4: +1.685 °C
> Fase: El Niño

In [ ]:
# ============================================================
# 12 — Gráfico do RONI/3.4 por temporada
# ============================================================

import plotly.graph_objects as go

fig = go.Figure()

# Série do RONI/3.4
fig.add_trace(go.Scatter(
    x=df_roni["Temporada"],
    y=df_roni["RONI/3.4"],
    mode="lines+markers",
    name="RONI/3.4 — Niño 3.4",
    line=dict(width=2.5),
    marker=dict(size=8)
))

# Limite de El Niño
fig.add_hline(
    y=0.5,
    line_dash="dash",
    annotation_text="+0,5 °C"
)

# Limite de La Niña
fig.add_hline(
    y=-0.5,
    line_dash="dash",
    annotation_text="-0,5 °C"
)

# Linha de referência 0 °C
fig.add_hline(
    y=0,
    line_dash="dot"
)

fig.update_layout(
    title="RONI/3.4 — Niño 3.4 por temporadas de 3 meses - médias móveis sobrepostas",
    legend_title="Fases do ENSO (El Niño, La Niña, Neutro)",
    xaxis_title="Temporada",
    yaxis_title="RONI/3.4 (°C)",
    template="plotly_white",
    hovermode="x unified"
)

fig.show()

In [ ]:
# --------------------------------------------------------------------------
# 13 - Download do histórico oficial do RONI 
#---------------------------------------------------------------------------

import requests
from io import StringIO
import os

RAIZ = r"C:\TI\Projetos Univesp\Projeto - 4"

# URL oficial do RONI (ERSSTv6)
url_roni = "https://www.cpc.ncep.noaa.gov/data/indices/RONI.ascii.txt"

# Baixar
resp = requests.get(url_roni)
resp.raise_for_status()

df_hist_roni = pd.read_csv(StringIO(resp.text), sep=r'\s+')

dir_pasta = os.path.join(RAIZ, "roni_oficial_1950_2026.csv")
df_hist_roni.to_csv(dir_pasta, index=False)

print(f"Total de registros: {len(df_hist_roni)}")
print(f"Colunas: {df_hist_roni.columns.tolist()}")
print(f"Ano mínimo: {df_hist_roni['YR'].min()}")
print(f"Ano máximo: {df_hist_roni['YR'].max()}")
print()
df_hist_roni.head(12)

Total de registros: 919
Colunas: ['SEAS', 'YR', 'ANOM']
Ano mínimo: 1950
Ano máximo: 2026

   SEAS    YR  ANOM
0   DJF  1950 -1.19
1   JFM  1950 -1.08
2   FMA  1950 -0.96
3   MAM  1950 -1.00
4   AMJ  1950 -0.99
5   MJJ  1950 -0.75
6   JJA  1950 -0.38
7   JAS  1950 -0.32
8   ASO  1950 -0.29
9   SON  1950 -0.38
10  OND  1950 -0.36
11  NDJ  1950 -0.50

In [ ]:
# 14 - Conversão das temporadas em datas

# Mapeamento: qual mês central de cada trimestre?
meses_centrais = {
    "DJF": 1,   # dez-jan-fev → centro em jan
    "JFM": 2,   # jan-fev-mar → centro em fev
    "FMA": 3,   # fev-mar-abr → centro em mar
    "MAM": 4,   # mar-abr-mai → centro em abr
    "AMJ": 5,   # abr-mai-jun → centro em mai
    "MJJ": 6,   # mai-jun-jul → centro em jun
    "JJA": 7,   # jun-jul-ago → centro em jul
    "JAS": 8,   # jul-ago-set → centro em ago
    "ASO": 9,   # ago-set-out → centro em set
    "SON": 10,  # set-out-nov → centro em out
    "OND": 11,  # out-nov-dez → centro em nov
    "NDJ": 12,  # nov-dez-jan → centro em dez
}

# Criar coluna de data
df_hist_roni["mes_central"] = df_hist_roni["SEAS"].map(meses_centrais)
df_hist_roni["data"] = pd.to_datetime(
    df_hist_roni["YR"].astype(str) + "-" +
    df_hist_roni["mes_central"].astype(str) + "-01"
)

print(df_hist_roni[["SEAS", "YR", "ANOM", "data"]].head(12))

   SEAS    YR  ANOM       data
0   DJF  1950 -1.19 1950-01-01
1   JFM  1950 -1.08 1950-02-01
2   FMA  1950 -0.96 1950-03-01
3   MAM  1950 -1.00 1950-04-01
4   AMJ  1950 -0.99 1950-05-01
5   MJJ  1950 -0.75 1950-06-01
6   JJA  1950 -0.38 1950-07-01
7   JAS  1950 -0.32 1950-08-01
8   ASO  1950 -0.29 1950-09-01
9   SON  1950 -0.38 1950-10-01
10  OND  1950 -0.36 1950-11-01
11  NDJ  1950 -0.50 1950-12-01

In [ ]:
# 15 - Classificação das fases no histórico oficial

def classificar(valor):
    if valor >= 0.5:
        return "El Niño"
    elif valor <= -0.5:
        return "La Niña"
    else:
        return "Neutro"

df_hist_roni["fase"] = df_hist_roni["ANOM"].apply(classificar)

print(df_hist_roni["fase"].value_counts())

fase
Neutro     444
El Niño    239
La Niña    236
Name: count, dtype: int64

In [ ]:
# 16 - Gráfico da série histórica oficial do RONI

import plotly.express as px

fig = px.line(
    df_hist_roni,
    x="data",
    y="ANOM",
    color="fase",
    title="RONI — Série temporal (1950–2026)",
    labels={
        "data": "Data",
        "ANOM": "RONI (°C)",
        "fase": "Fase",
    },
    color_discrete_map={
        "El Niño": "#d62728",   # vermelho
        "La Niña": "#1f77b4",   # azul
        "Neutro": "gray",       # cinza
    },
)

# Adicionar linhas de referência (+0.5 e -0.5)
fig.add_hline(y=0.5, line_dash="dash", line_color="red", opacity=0.5)
fig.add_hline(y=-0.5, line_dash="dash", line_color="blue", opacity=0.5)
fig.add_hline(y=0, line_dash="dot", line_color="black", opacity=0.3)

fig.update_layout(
    height=500,
    hovermode="x unified",
    xaxis_title="Ano",
    yaxis_title="RONI (°C)",
)

fig.show()

In [ ]:
# 17 - Comparação inicial dos anos históricos com 2026

# ============================================================
# 1. Alvo: a sequência de 2026 (do df_roni calculado)
# ============================================================

# df_roni tem índice = observation_date, colunas Temporada, RONI/3.4, Fase
alvo = df_roni["RONI/3.4"].values  # shape (7,)
temporadas_alvo = df_roni["Temporada"].tolist()
print("Alvo (2026):", dict(zip(temporadas_alvo, alvo.round(3))))

# ============================================================
# 2. Preparar o histórico oficial (df_hist_roni)
# ============================================================

# Ordenar temporadas na ordem correta do ano civil
ordem_seas = ["JFM", "FMA", "MAM", "AMJ", "MJJ", "JJA", "JAS"]

# Para cada ano, pegar a janela JFM..JAS
historicos = {}
for ano, grupo in df_hist_roni.groupby("YR"):
    if ano == 2026:
        continue  # pular o ano alvo
    g = grupo.set_index("SEAS").reindex(ordem_seas)
    if g["ANOM"].notna().all():
        historicos[ano] = g["ANOM"].values

print(f"Anos com janela completa JFM–JAS: {len(historicos)}")

# ============================================================
# 3. Comparar cada ano com o alvo (RMSE)
# ============================================================

resultados = []
for ano, seq in historicos.items():
    rmse = np.sqrt(np.mean((seq - alvo) ** 2))
    # correlação (opcional, ajuda a ver similaridade de forma)
    corr = np.corrcoef(seq, alvo)[0, 1]
    resultados.append({
        "Ano": ano,
        **{f"{t}": round(v, 2) for t, v in zip(ordem_seas, seq)},
        "RMSE": round(rmse, 3),
        "Correlacao": round(corr, 3),
    })

df_rank = pd.DataFrame(resultados).sort_values("RMSE").reset_index(drop=True)

print("\n===== TOP 10 ANOS MAIS PARECIDOS COM 2026 (JFM–JAS) =====")
df_rank.head(80).sort_values("Ano").set_index("Ano")

Alvo (2026): {'JFM': np.float64(-0.692), 'FMA': np.float64(-0.387), 'MAM': np.float64(-0.02), 'AMJ': np.float64(0.488), 'MJJ': np.float64(0.935), 'JJA': np.float64(1.377), 'JAS': np.float64(1.685)}
Anos com janela completa JFM–JAS: 76

===== TOP 10 ANOS MAIS PARECIDOS COM 2026 (JFM–JAS) =====

       JFM   FMA   MAM   AMJ   MJJ   JJA   JAS   RMSE  Correlacao
Ano
1950 -1.08 -0.96 -1.00 -0.99 -0.75 -0.38 -0.32  1.392       0.915
1951  0.09  0.48  0.63  0.59  0.69  0.79  0.97  0.622       0.904
1952  0.33  0.46  0.24 -0.03 -0.45 -0.41 -0.14  1.227      -0.854
1953  0.67  0.68  0.72  0.94  0.84  0.68  0.73  0.858       0.229
1954  0.63  0.31 -0.02 -0.24 -0.21 -0.45 -0.62  1.348      -0.959
...    ...   ...   ...   ...   ...   ...   ...    ...         ...
2021 -1.18 -1.08 -0.89 -0.68 -0.57 -0.60 -0.76  1.463       0.837
2022 -1.13 -1.19 -1.26 -1.17 -0.95 -0.86 -0.94  1.714       0.813
2023 -0.68 -0.55 -0.31 -0.04  0.28  0.54  0.79  0.576       0.998
2024  0.78  0.42  0.04 -0.28 -0.45 -0.49 -0.56  1.407      -0.947
2025 -0.85 -0.66 -0.50 -0.48 -0.36 -0.41 -0.59  1.271       0.653

[76 rows x 9 columns]

In [ ]:
# ============================================================
# 18 Cálculo detalhado das métricas de similaridade
# ============================================================
ordem_seas = ["JFM", "FMA", "MAM", "AMJ", "MJJ", "JJA", "JAS"]

# ============================================================
# 1. Alvo: sequência de 2026 (ordenada corretamente)
# ============================================================
alvo = (
    df_roni
    .set_index("Temporada")
    .reindex(ordem_seas)["RONI/3.4"]
    .values
)

print("Alvo (2026):")
for t, v in zip(ordem_seas, alvo):
    print(f"  {t}: {v:+.3f}")

# ============================================================
# 2. Histórico oficial — janelas JFM..JAS por ano
# ============================================================
historicos = {}
for ano, grupo in df_hist_roni.groupby("YR"):
    if ano == 2026:            # pular o ano alvo
        continue
    g = grupo.set_index("SEAS").reindex(ordem_seas)
    if g["ANOM"].notna().all():
        historicos[ano] = g["ANOM"].values

print(f"\nAnos com janela completa JFM–JAS: {len(historicos)}")

# ============================================================
# 3. Métricas de similaridade
# ============================================================
resultados = []
for ano, seq in historicos.items():
    rmse = float(np.sqrt(np.mean((seq - alvo) ** 2)))
    corr = float(np.corrcoef(seq, alvo)[0, 1])

    # Diagnósticos extras
    std       = float(np.std(seq, ddof=1))              # variabilidade interna
    amplitude = float(seq.max() - seq.min())            # range total
    trim_divergente = int(sum(abs(s - a) > 0.5 for s, a in zip(seq, alvo)))  # trimestres com grande divergência

    resultados.append({
        "Ano": ano,
        **{t: round(v, 2) for t, v in zip(ordem_seas, seq)},
        "RMSE": round(rmse, 3),
        "Correlacao": round(corr, 3),
        "Std": round(std, 3),
        "Amplitude": round(amplitude, 3),
        "trim_divergente": trim_divergente,
    })

df_rank = (
    pd.DataFrame(resultados)
    .sort_values("RMSE")
    .reset_index(drop=True)
)

# ============================================================
# 4. Visualização
# ============================================================
print("\n===== TOP 10 ANOS MAIS PARECIDOS COM 2026 (JFM–JAS) =====")
print(df_rank.head(10).to_string(index=False))

print("\n===== TODOS OS ANOS (ordenados por Ano) =====")
df_rank.sort_values("Correlacao").set_index("Ano")

Alvo (2026):
  JFM: -0.692
  FMA: -0.387
  MAM: -0.020
  AMJ: +0.488
  MJJ: +0.935
  JJA: +1.377
  JAS: +1.685

Anos com janela completa JFM–JAS: 76

===== TOP 10 ANOS MAIS PARECIDOS COM 2026 (JFM–JAS) =====
 Ano   JFM   FMA   MAM   AMJ  MJJ  JJA  JAS  RMSE  Correlacao   Std  Amplitude  trim_divergente
1965  0.10  0.22  0.36  0.64 1.01 1.33 1.49 0.415       0.993 0.550       1.39                2
1997 -0.03  0.17  0.47  0.83 1.20 1.50 1.84 0.416       0.999 0.696       1.87                2
1972  0.03  0.32  0.51  0.66 0.87 1.14 1.40 0.459       0.990 0.473       1.37                3
1963 -0.12  0.04  0.06  0.01 0.37 0.73 1.08 0.514       0.916 0.444       1.20                4
1982  0.22  0.23  0.46  0.74 0.84 0.89 1.14 0.541       0.981 0.351       0.92                3
2002  0.01  0.03  0.05  0.22 0.44 0.64 0.80 0.575       0.972 0.319       0.79                3
2023 -0.68 -0.55 -0.31 -0.04 0.28 0.54 0.79 0.576       0.998 0.556       1.47                4
1976 -0.65 -0.26 -0.14  0.01 0.27 0.52 0.72 0.582       0.987 0.473       1.37                3
1951  0.09  0.48  0.63  0.59 0.69 0.79 0.97 0.622       0.904 0.276       0.88                5
1968 -0.36 -0.32 -0.26  0.07 0.32 0.56 0.46 0.643       0.973 0.387       0.92                3

===== TODOS OS ANOS (ordenados por Ano) =====

,JFM,FMA,MAM,AMJ,MJJ,JJA,JAS,RMSE,Correlacao,Std,Amplitude,trim_divergente
Ano,,,,,,,,,,,,
1959,0.83,0.64,0.48,0.33,0.09,-0.11,-0.23,1.209,-0.998,0.392,1.06,5
1983,2.15,1.67,1.30,0.87,0.47,0.03,-0.23,1.686,-0.997,0.869,2.38,5
1998,1.82,1.22,0.81,0.07,-0.46,-1.05,-1.14,1.911,-0.994,1.143,2.96,6
1992,2.08,1.94,1.76,1.40,0.93,0.52,0.30,1.680,-0.993,0.705,1.78,6
1975,-0.13,-0.29,-0.42,-0.61,-0.73,-0.87,-0.88,1.516,-0.989,0.291,0.75,5
...,...,...,...,...,...,...,...,...,...,...,...,...
2008,-1.62,-1.39,-1.04,-0.80,-0.46,-0.24,-0.17,1.340,0.992,0.563,1.45,7
1965,0.10,0.22,0.36,0.64,1.01,1.33,1.49,0.415,0.993,0.550,1.39,2
2006,-0.87,-0.69,-0.49,-0.19,-0.05,0.15,0.36,0.848,0.997,0.449,1.23,4
2023,-0.68,-0.55,-0.31,-0.04,0.28,0.54,0.79,0.576,0.998,0.556,1.47,4
1997,-0.03,0.17,0.47,0.83,1.20,1.50,1.84,0.416,0.999,0.696,1.87,2

In [ ]:
# 19 Seleção final de anos análogos
LIMIAR_CORR = 0.990
LIMIAR_RMSE = 0.600
LIMIAR_TRIM = 3
LIMIAR_AMPL = 1.30

sel_amplo = df_rank[
    (df_rank["Correlacao"] >= LIMIAR_CORR) &
    (df_rank["RMSE"]       <= LIMIAR_RMSE) &
    (df_rank["trim_divergente"] <= LIMIAR_TRIM) &
    (df_rank["Amplitude"]  >= LIMIAR_AMPL)
].sort_values("RMSE").reset_index(drop=True)

print(f"Análogos selecionados: {len(sel_amplo)}")
print(sel_amplo[["Ano", "RMSE", "Correlacao", "Amplitude", "trim_divergente"]].to_string(index=False))

Análogos selecionados: 3
 Ano  RMSE  Correlacao  Amplitude  trim_divergente
1965 0.415       0.993       1.39                2
1997 0.416       0.999       1.87                2
1972 0.459       0.990       1.37                3

In [ ]:
# 20 - Comparação dos Correlatos históricos vs 2026

import plotly.graph_objects as go

ordem_seas = ["JFM", "FMA", "MAM", "AMJ", "MJJ", "JJA", "JAS"]

# Alvo 2026 na ordem corretaa
alvo = (
    df_roni.set_index("Temporada")
    .reindex(ordem_seas)["RONI/3.4"]
    .values
)

# Média dos análogos (por temporada)
mat_med = sel_amplo[ordem_seas].values.astype(float)
media_an = mat_med.mean(axis=0)

fig = go.Figure()

# ------------------------------------------------------------
# 1. Análogos individuais
# ------------------------------------------------------------
for _, row in sel_amplo.sort_values("Ano").iterrows():
    seq = [row[t] for t in ordem_seas]
    fig.add_trace(go.Scatter(
        x=ordem_seas,
        y=seq,
        mode="lines+markers",
        name=f'{int(row["Ano"])}',
        line=dict(width=1.8),
        opacity=0.85,
        hovertemplate=(
            f'<b>{int(row["Ano"])}</b><br>'
            '%{x} = %{y:.3f}<br>'
            f'Correlação: {row["Correlacao"]:.3f}<br>'
            f'RMSE: {row["RMSE"]:.3f}'
            '<extra></extra>'
        ),
    ))

# ------------------------------------------------------------
# 2. Média dos análogos  (hex no lugar de "tab:blue")
# ------------------------------------------------------------
fig.add_trace(go.Scatter(
    x=ordem_seas,
    y=media_an,
    mode="lines+markers",
    name="Média dos análogos",
    line=dict(width=2.5, color="#1f77b4", dash="dash"),
    marker=dict(size=8, color="#1f77b4"),
    hovertemplate=(
        '<b>Média dos análogos</b><br>'
        '%{x} = %{y:.3f}'
        '<extra></extra>'
    ),
))

# ------------------------------------------------------------
# 3. 2026 em destaque
# ------------------------------------------------------------
fig.add_trace(go.Scatter(
    x=ordem_seas,
    y=alvo,
    mode="lines+markers",
    name="2026 (alvo)",
    line=dict(width=3.5, color="#000000"),
    marker=dict(size=9, color="#000000"),
    hovertemplate=(
        '<b>2026 (alvo)</b><br>'
        '%{x} = %{y:.3f}'
        '<extra></extra>'
    ),
))

# ------------------------------------------------------------
# 4. Limiares ENSO
# ------------------------------------------------------------
fig.add_hline(y=0.5,  line_dash="dot", line_color="#d62728", opacity=0.5)
fig.add_hline(y=-0.5, line_dash="dot", line_color="#1f77b4", opacity=0.5)
fig.add_hline(y=0,    line_dash="dot", line_color="#7f7f7f", opacity=0.3)

fig.update_layout(
    title=f"Análogos históricos de 2026 (r >= {LIMIAR}) — JFM a JAS",
    xaxis_title="Temporada",
    yaxis_title="RONI/3.4 (°C)",
    template="plotly_white",
    hovermode="closest",
    legend_title="Ano",
)

fig.show()

In [ ]:
# ===============================================================================================================================
# 21 - Predizer os trimestres faltantes de 2026 com base nos análogos de sel_amplo ---
# ===============================================================================================================================

# ============================================================
# 1. Análogos selecionados (dinâmico a partir de sel_amplo)
# ============================================================
anos_analogos = sel_amplo["Ano"].tolist()
print(f"Análogos usados: {anos_analogos}")

# ============================================================
# 2. Montar matriz de treino
# ============================================================
ordem_seas  = ["JFM", "FMA", "MAM", "AMJ", "MJJ", "JJA", "JAS"]
seas_futuro = ["ASO", "SON", "OND", "NDJ"]

X_train = []
Y_train = []

for ano in anos_analogos:
    hist = df_hist_roni[df_hist_roni["YR"] == ano].set_index("SEAS")
    x_jas = hist.loc["JAS", "ANOM"]
    y_fut = [hist.loc[s, "ANOM"] for s in seas_futuro]

    X_train.append(x_jas)
    Y_train.append(y_fut)

X_train = np.array(X_train)          # shape (n_análogos,)
Y_train = np.array(Y_train)          # shape (n_análogos, 4)

# ============================================================
# 3. Valor de JAS no alvo 2026
# ============================================================
x_alvo = alvo[-1]
print(f"JAS de 2026 = {x_alvo:.3f}")

# ============================================================
# 4. Regressão linear por trimestre futuro
# ============================================================
previsoes = []

for i, seas in enumerate(seas_futuro):
    a, b = np.polyfit(X_train, Y_train[:, i], deg=1)
    y_prev = a * x_alvo + b
    previsoes.append(y_prev)
    print(f"{seas}: y = {a:.3f} * x + {b:.3f}  →  2026: {y_prev:+.3f} °C")

# ============================================================
# 5. Tabela final
# ============================================================
df_proj = pd.DataFrame({
    "Temporada": seas_futuro,
    "Previsão": np.round(previsoes, 3),
})

df_proj["Fase"] = np.where(
    df_proj["Previsão"] >= 0.5, "El Niño",
    np.where(df_proj["Previsão"] <= -0.5, "La Niña", "Neutro")
)

print("\n===== PROJEÇÃO DE 2026 (ASO–NDJ) =====")
print(df_proj.to_string(index=False))

Análogos usados: [1965, 1997, 1972]
JAS de 2026 = 1.685
ASO: y = 0.952 * x + 0.323  →  2026: +1.926 °C
SON: y = 0.943 * x + 0.480  →  2026: +2.069 °C
OND: y = 0.666 * x + 1.020  →  2026: +2.142 °C
NDJ: y = 1.031 * x + 0.365  →  2026: +2.102 °C

===== PROJEÇÃO DE 2026 (ASO–NDJ) =====
Temporada  Previsão    Fase
      ASO     1.926 El Niño
      SON     2.069 El Niño
      OND     2.142 El Niño
      NDJ     2.102 El Niño

In [ ]:
# 22 - Predição em Plotagem

import plotly.graph_objects as go

# ============================================================
# 1. Regressão linear com os análogos (ajuste aqui os anos)
# ============================================================
anos_analogos = [1965, 1997]      # ou o que o filtro retornar

ordem_seas   = ["JFM", "FMA", "MAM", "AMJ", "MJJ", "JJA", "JAS"]
seas_futuro  = ["ASO", "SON", "OND", "NDJ"]

X_train = []
Y_train = []
for ano in anos_analogos:
    hist = df_hist_roni[df_hist_roni["YR"] == ano].set_index("SEAS")
    X_train.append(hist.loc["JAS", "ANOM"])
    Y_train.append([hist.loc[s, "ANOM"] for s in seas_futuro])

X_train = np.array(X_train)
Y_train = np.array(Y_train)

x_alvo = alvo[-1]   # JAS de 2026

previsoes = []
for i in range(len(seas_futuro)):
    a, b = np.polyfit(X_train, Y_train[:, i], deg=1)
    previsoes.append(a * x_alvo + b)

# ============================================================
# 2. Gráfico
# ============================================================
fig = go.Figure()

# --- Série observada de 2026 ---
fig.add_trace(go.Scatter(
    x=df_roni["Temporada"],
    y=df_roni["RONI/3.4"],
    mode="lines+markers",
    name="2026 — observado",
    line=dict(width=2.5, color="#000000"),
    marker=dict(size=8, color="#000000"),
))

# --- Projeção (conecta o último ponto observado ao primeiro previsto) ---
x_proj = [df_roni["Temporada"].iloc[-1]] + seas_futuro
y_proj = [df_roni["RONI/3.4"].iloc[-1]] + previsoes

fig.add_trace(go.Scatter(
    x=x_proj,
    y=y_proj,
    mode="lines+markers",
    name="2026 — projetado (regressão)",
    line=dict(width=2.5, color="#d62728", dash="dash"),
    marker=dict(size=9, color="#d62728", symbol="diamond"),
    hovertemplate="Temporada: %{x}<br>RONI/3.4: %{y:.2f} °C<extra></extra>",
))

# --- Limiares ENSO ---
fig.add_hline(y=0.5,  line_dash="dash", annotation_text="+0,5 °C")
fig.add_hline(y=-0.5, line_dash="dash", annotation_text="-0,5 °C")
fig.add_hline(y=0,    line_dash="dot")

fig.update_layout(
    title="RONI/3.4 — 2026 observado + projeção ASO–NDJ (regressão sobre análogos)",
    legend_title="Série",
    xaxis_title="Temporada",
    yaxis_title="RONI/3.4 (°C)",
    template="plotly_white",
    hovermode="x unified",
)

fig.show()

In [ ]:
# 22 Mapa das anomalias médias nas regiões Niño

import plotly.graph_objects as go
import math
import random

random.seed(42)

df["observation_date"] = pd.to_datetime(df["observation_date"])
df = df.sort_values("observation_date").reset_index(drop=True)

nomes_mes = {1:"jan", 2:"fev", 3:"mar", 4:"abr", 5:"mai", 6:"jun", 7:"jul", 8:"ago", 9:"set", 10:"out", 11:"nov", 12:"dez"}
d0, d1 = df["observation_date"].min(), df["observation_date"].max()
periodo = f"{nomes_mes[d0.month]}/{d0.year} a {nomes_mes[d1.month]}/{d1.year}"

medias = df[["nino12", "nino3", "nino34", "nino4"]].mean()

def class_oni(v):
    if v >= 0.5:
        return "El Niño"
    if v <= -0.5:
        return "La Niña"
    return "Neutro"

regioes = [
    ("Niño 1+2", "nino12", (-10, 0), (-90, -80)),
    ("Niño 3",   "nino3",  (-5, 5),  (-150, -90)),
    ("Niño 3.4", "nino34", (-5, 5),  (-170, -120)),
    ("Niño 4",   "nino4",  (-5, 5),  (160, -150)),
]

def cor_anomalia(v, vmax):
    t = max(-1.0, min(1.0, v / vmax))
    azul   = (21, 101, 192)
    neutro = (236, 236, 236)
    quente = (203, 24, 43)
    if t < 0:
        c = tuple(int(azul[i] + (neutro[i] - azul[i]) * (-t)) for i in range(3))
    else:
        c = tuple(int(neutro[i] + (quente[i] - neutro[i]) * t) for i in range(3))
    return f"rgb({c[0]},{c[1]},{c[2]})"

def centroide(lat, lon):
    lat0, lat1 = lat
    lon0, lon1 = lon
    if lon0 > lon1:
        lon1 += 360
    return ((lat0 + lat1) / 2, (lon0 + lon1) / 2)

def geometria_regiao(lat, lon, raio_frac=0.28):
    lat0, lat1 = lat
    lon0, lon1 = lon
    if lon0 > lon1:
        lon1 += 360
    la_min, la_max = min(lat0, lat1), max(lat0, lat1)
    lo_min, lo_max = min(lon0, lon1), max(lon0, lon1)
    r = min(la_max - la_min, lo_max - lo_min) * raio_frac
    r = min(r, (la_max - la_min) / 2, (lo_max - lo_min) / 2)
    return la_min, la_max, lo_min, lo_max, r

def retangulo_arredondado(lat, lon, n_linha=30, n_arco=18):
    la_min, la_max, lo_min, lo_max, r = geometria_regiao(lat, lon)
    pts = []

    def add(x, y):
        pts.append((y, x))

    def linha(x0, x1, y):
        for i in range(n_linha + 1):
            t = i / n_linha
            add(x0 + (x1 - x0) * t, y)

    def linha_v(x, y0, y1):
        for i in range(n_linha + 1):
            t = i / n_linha
            add(x, y0 + (y1 - y0) * t)

    def arco(cx, cy, a0, a1):
        for i in range(n_arco + 1):
            a = math.radians(a0 + (a1 - a0) * i / n_arco)
            add(cx + r * math.cos(a), cy + r * math.sin(a))

    linha(lo_min + r, lo_max - r, la_min)
    arco(lo_max - r, la_min + r, -90, 0)
    linha_v(lo_max, la_min + r, la_max - r)
    arco(lo_max - r, la_max - r, 0, 90)
    linha(lo_max - r, lo_min + r, la_max)
    arco(lo_min + r, la_max - r, 90, 180)
    linha_v(lo_min, la_max - r, la_min + r)
    arco(lo_min + r, la_min + r, 180, 270)
    return pts

def nuvem(lat, lon, geom=None, passo=2.0, jitter=0.7):
    lat0, lat1 = lat
    lon0, lon1 = lon
    if lon0 > lon1:
        lon1 += 360
    la_min, la_max, lo_min, lo_max, r = geom or geometria_regiao(lat, lon)
    cf = math.cos(math.radians((la_min + la_max) / 2))
    cornos = [
        (lo_max - r, la_min + r, +1, -1),
        (lo_max - r, la_max - r, +1, +1),
        (lo_min + r, la_max - r, -1, +1),
        (lo_min + r, la_min + r, -1, -1),
    ]
    r2 = (r * cf) ** 2
    lats, lons = [], []
    y = min(lat0, lat1)
    while y <= max(lat0, lat1):
        x = min(lon0, lon1)
        while x <= max(lon0, lon1):
            yy = y + random.uniform(-jitter, jitter)
            xx = x + random.uniform(-jitter * 0.7, jitter * 0.7)
            dentro = True
            for cx, cy, sx, sy in cornos:
                dx = (xx - cx) * cf * sx
                dy = (yy - cy) * sy
                if dx >= 0 and dy >= 0 and dx * dx + dy * dy > r2:
                    dentro = False
                    break
            if dentro:
                lats.append(yy)
                lons.append(xx)
            x += passo
        y += passo
    return lats, lons

valores = [medias[c] for _, c, _, _ in regioes]
vmax = max(1.0, max(abs(v) for v in valores))

fig = go.Figure()

for nome, col, lat, lon in regioes:
    v = medias[col]
    cls = class_oni(v)
    cor = cor_anomalia(v, vmax)

    r, g, b = map(int, cor.strip("rgb()").split(","))
    alpha = 0x26 / 255.0
    rgba_fillcolor = f"rgba({r},{g},{b},{alpha:.2f})"

    geom = geometria_regiao(lat, lon)

    parte = retangulo_arredondado(lat, lon)
    fig.add_trace(go.Scattermap(
        lat=[p[0] for p in parte],
        lon=[p[1] for p in parte],
        mode="lines",
        line=dict(color=cor, width=2.2),
        fill="toself",
        fillcolor=rgba_fillcolor,
        showlegend=False,
        hoverinfo="skip",
    ))

    lats, lons = nuvem(lat, lon, geom)
    latc, lonc = centroide(lat, lon)

    fig.add_trace(go.Scattermap(
        lat=lats, lon=lons,
        mode="markers",
        name=f'{nome}: {v:+.2f}°C | {cls}',
        marker=dict(size=5, color=cor, opacity=0.9),
        hovertemplate=f'<b>{nome}</b><br>Anomalia média SST: {v:+.2f}°C<br>Classificação ONI: {cls}<extra></extra>',
    ))

    fig.add_trace(go.Scattermap(
        lat=[latc], lon=[lonc],
        mode="text",
        text=[f'{nome}<br>{v:+.2f}°C ({cls})'],
        textposition="top center",
        textfont=dict(size=13, color="#0d1b2a"),
        showlegend=False,
        hoverinfo="skip",
    ))

fig.update_layout(
    title=dict(
        text=f"Nuvem de Anomalia TSM nas Regiões El Niño (Média {periodo})",
        font=dict(size=20, family="Arial Black"),
        x=0.5, xanchor="center",
    ),
    map=dict(
        style="open-street-map",
        center=dict(lat=-2, lon=-140),
        zoom=1.4,
        bearing=0,
        pitch=0,
    ),
    legend=dict(
        title=dict(text="Anomalia média SST (°C) e Classificação ONI", font=dict(size=14)),
        font=dict(size=12),
        bgcolor="rgba(255,255,255,0.85)",
        bordercolor="#00000033",
        borderwidth=1,
        x=0.01, y=0.99,
        xanchor="left", yanchor="top",
    ),
    margin=dict(l=0, r=0, t=60, b=0),
    height=600,
    width=1000,
)

fig.show()